/* This file was generated by SableCC (http://www.sablecc.org/). */

package ufs.compiladores.x.analysis;

import java.util.*;
import ufs.compiladores.x.node.*;

public class DepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getPInicioPrograma().apply(this);
        node.getEOF().apply(this);
        outStart(node);
    }

    public void inAProgramaInicioPrograma(AProgramaInicioPrograma node)
    {
        defaultIn(node);
    }

    public void outAProgramaInicioPrograma(AProgramaInicioPrograma node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAProgramaInicioPrograma(AProgramaInicioPrograma node)
    {
        inAProgramaInicioPrograma(node);
        {
            List<PPrograma> copy = new ArrayList<PPrograma>(node.getPrograma());
            for(PPrograma e : copy)
            {
                e.apply(this);
            }
        }
        outAProgramaInicioPrograma(node);
    }

    public void inAVazioInicioPrograma(AVazioInicioPrograma node)
    {
        defaultIn(node);
    }

    public void outAVazioInicioPrograma(AVazioInicioPrograma node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVazioInicioPrograma(AVazioInicioPrograma node)
    {
        inAVazioInicioPrograma(node);
        if(node.getVazio() != null)
        {
            node.getVazio().apply(this);
        }
        outAVazioInicioPrograma(node);
    }

    public void inAVazioVazio(AVazioVazio node)
    {
        defaultIn(node);
    }

    public void outAVazioVazio(AVazioVazio node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVazioVazio(AVazioVazio node)
    {
        inAVazioVazio(node);
        outAVazioVazio(node);
    }

    public void inADecVariavelUnicoPrograma(ADecVariavelUnicoPrograma node)
    {
        defaultIn(node);
    }

    public void outADecVariavelUnicoPrograma(ADecVariavelUnicoPrograma node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADecVariavelUnicoPrograma(ADecVariavelUnicoPrograma node)
    {
        inADecVariavelUnicoPrograma(node);
        if(node.getDecVar() != null)
        {
            node.getDecVar().apply(this);
        }
        outADecVariavelUnicoPrograma(node);
    }

    public void inADecConstanteUnicoPrograma(ADecConstanteUnicoPrograma node)
    {
        defaultIn(node);
    }

    public void outADecConstanteUnicoPrograma(ADecConstanteUnicoPrograma node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADecConstanteUnicoPrograma(ADecConstanteUnicoPrograma node)
    {
        inADecConstanteUnicoPrograma(node);
        if(node.getDecConst() != null)
        {
            node.getDecConst().apply(this);
        }
        outADecConstanteUnicoPrograma(node);
    }

    public void inADecProcedimentoUnicoPrograma(ADecProcedimentoUnicoPrograma node)
    {
        defaultIn(node);
    }

    public void outADecProcedimentoUnicoPrograma(ADecProcedimentoUnicoPrograma node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADecProcedimentoUnicoPrograma(ADecProcedimentoUnicoPrograma node)
    {
        inADecProcedimentoUnicoPrograma(node);
        if(node.getDecProcedimento() != null)
        {
            node.getDecProcedimento().apply(this);
        }
        outADecProcedimentoUnicoPrograma(node);
    }

    public void inADecFuncaoUnicoPrograma(ADecFuncaoUnicoPrograma node)
    {
        defaultIn(node);
    }

    public void outADecFuncaoUnicoPrograma(ADecFuncaoUnicoPrograma node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADecFuncaoUnicoPrograma(ADecFuncaoUnicoPrograma node)
    {
        inADecFuncaoUnicoPrograma(node);
        if(node.getDecFuncao() != null)
        {
            node.getDecFuncao().apply(this);
        }
        outADecFuncaoUnicoPrograma(node);
    }

    public void inADecVar(ADecVar node)
    {
        defaultIn(node);
    }

    public void outADecVar(ADecVar node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADecVar(ADecVar node)
    {
        inADecVar(node);
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        if(node.getTipo() != null)
        {
            node.getTipo().apply(this);
        }
        if(node.getOpcaoVar() != null)
        {
            node.getOpcaoVar().apply(this);
        }
        {
            List<PContOpcaoVar> copy = new ArrayList<PContOpcaoVar>(node.getContOpcaoVar());
            for(PContOpcaoVar e : copy)
            {
                e.apply(this);
            }
        }
        outADecVar(node);
    }

    public void inADecConst(ADecConst node)
    {
        defaultIn(node);
    }

    public void outADecConst(ADecConst node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADecConst(ADecConst node)
    {
        inADecConst(node);
        if(node.getCons() != null)
        {
            node.getCons().apply(this);
        }
        if(node.getTipo() != null)
        {
            node.getTipo().apply(this);
        }
        if(node.getInicializacao() != null)
        {
            node.getInicializacao().apply(this);
        }
        {
            List<PContInicializacao> copy = new ArrayList<PContInicializacao>(node.getContInicializacao());
            for(PContInicializacao e : copy)
            {
                e.apply(this);
            }
        }
        outADecConst(node);
    }

    public void inAAtriExpIniInicializacao(AAtriExpIniInicializacao node)
    {
        defaultIn(node);
    }

    public void outAAtriExpIniInicializacao(AAtriExpIniInicializacao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAtriExpIniInicializacao(AAtriExpIniInicializacao node)
    {
        inAAtriExpIniInicializacao(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAAtriExpIniInicializacao(node);
    }

    public void inAAtriIniArrayExtInicializacao(AAtriIniArrayExtInicializacao node)
    {
        defaultIn(node);
    }

    public void outAAtriIniArrayExtInicializacao(AAtriIniArrayExtInicializacao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAtriIniArrayExtInicializacao(AAtriIniArrayExtInicializacao node)
    {
        inAAtriIniArrayExtInicializacao(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getArrayExt() != null)
        {
            node.getArrayExt().apply(this);
        }
        outAAtriIniArrayExtInicializacao(node);
    }

    public void inAAtriIniArrayCompInicializacao(AAtriIniArrayCompInicializacao node)
    {
        defaultIn(node);
    }

    public void outAAtriIniArrayCompInicializacao(AAtriIniArrayCompInicializacao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAtriIniArrayCompInicializacao(AAtriIniArrayCompInicializacao node)
    {
        inAAtriIniArrayCompInicializacao(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getArrayComp() != null)
        {
            node.getArrayComp().apply(this);
        }
        outAAtriIniArrayCompInicializacao(node);
    }

    public void inAContInicializacao(AContInicializacao node)
    {
        defaultIn(node);
    }

    public void outAContInicializacao(AContInicializacao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAContInicializacao(AContInicializacao node)
    {
        inAContInicializacao(node);
        if(node.getInicializacao() != null)
        {
            node.getInicializacao().apply(this);
        }
        outAContInicializacao(node);
    }

    public void inAArrayExt(AArrayExt node)
    {
        defaultIn(node);
    }

    public void outAArrayExt(AArrayExt node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAArrayExt(AArrayExt node)
    {
        inAArrayExt(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        {
            List<PContExp> copy = new ArrayList<PContExp>(node.getContExp());
            for(PContExp e : copy)
            {
                e.apply(this);
            }
        }
        outAArrayExt(node);
    }

    public void inAArrayComp(AArrayComp node)
    {
        defaultIn(node);
    }

    public void outAArrayComp(AArrayComp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAArrayComp(AArrayComp node)
    {
        inAArrayComp(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getContArrayComp() != null)
        {
            node.getContArrayComp().apply(this);
        }
        outAArrayComp(node);
    }

    public void inAArrayCompEscolhaContArrayComp(AArrayCompEscolhaContArrayComp node)
    {
        defaultIn(node);
    }

    public void outAArrayCompEscolhaContArrayComp(AArrayCompEscolhaContArrayComp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAArrayCompEscolhaContArrayComp(AArrayCompEscolhaContArrayComp node)
    {
        inAArrayCompEscolhaContArrayComp(node);
        if(node.getArrayComp() != null)
        {
            node.getArrayComp().apply(this);
        }
        outAArrayCompEscolhaContArrayComp(node);
    }

    public void inAExpEscolhaContArrayComp(AExpEscolhaContArrayComp node)
    {
        defaultIn(node);
    }

    public void outAExpEscolhaContArrayComp(AExpEscolhaContArrayComp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpEscolhaContArrayComp(AExpEscolhaContArrayComp node)
    {
        inAExpEscolhaContArrayComp(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAExpEscolhaContArrayComp(node);
    }

    public void inATipoBaseTipo(ATipoBaseTipo node)
    {
        defaultIn(node);
    }

    public void outATipoBaseTipo(ATipoBaseTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATipoBaseTipo(ATipoBaseTipo node)
    {
        inATipoBaseTipo(node);
        if(node.getTipoBase() != null)
        {
            node.getTipoBase().apply(this);
        }
        outATipoBaseTipo(node);
    }

    public void inATipoCompostoTipo(ATipoCompostoTipo node)
    {
        defaultIn(node);
    }

    public void outATipoCompostoTipo(ATipoCompostoTipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATipoCompostoTipo(ATipoCompostoTipo node)
    {
        inATipoCompostoTipo(node);
        if(node.getTipo() != null)
        {
            node.getTipo().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outATipoCompostoTipo(node);
    }

    public void inAIntTipoBase(AIntTipoBase node)
    {
        defaultIn(node);
    }

    public void outAIntTipoBase(AIntTipoBase node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIntTipoBase(AIntTipoBase node)
    {
        inAIntTipoBase(node);
        if(node.getInt() != null)
        {
            node.getInt().apply(this);
        }
        outAIntTipoBase(node);
    }

    public void inABoolTipoBase(ABoolTipoBase node)
    {
        defaultIn(node);
    }

    public void outABoolTipoBase(ABoolTipoBase node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABoolTipoBase(ABoolTipoBase node)
    {
        inABoolTipoBase(node);
        if(node.getBool() != null)
        {
            node.getBool().apply(this);
        }
        outABoolTipoBase(node);
    }

    public void inARealTipoBase(ARealTipoBase node)
    {
        defaultIn(node);
    }

    public void outARealTipoBase(ARealTipoBase node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARealTipoBase(ARealTipoBase node)
    {
        inARealTipoBase(node);
        if(node.getReal() != null)
        {
            node.getReal().apply(this);
        }
        outARealTipoBase(node);
    }

    public void inADecProcedimento(ADecProcedimento node)
    {
        defaultIn(node);
    }

    public void outADecProcedimento(ADecProcedimento node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADecProcedimento(ADecProcedimento node)
    {
        inADecProcedimento(node);
        if(node.getProcedure() != null)
        {
            node.getProcedure().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getParametros() != null)
        {
            node.getParametros().apply(this);
        }
        if(node.getComando() != null)
        {
            node.getComando().apply(this);
        }
        outADecProcedimento(node);
    }

    public void inADecFuncao(ADecFuncao node)
    {
        defaultIn(node);
    }

    public void outADecFuncao(ADecFuncao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADecFuncao(ADecFuncao node)
    {
        inADecFuncao(node);
        if(node.getFunction() != null)
        {
            node.getFunction().apply(this);
        }
        if(node.getTipo() != null)
        {
            node.getTipo().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getParametros() != null)
        {
            node.getParametros().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outADecFuncao(node);
    }

    public void inAParamVazioParametros(AParamVazioParametros node)
    {
        defaultIn(node);
    }

    public void outAParamVazioParametros(AParamVazioParametros node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParamVazioParametros(AParamVazioParametros node)
    {
        inAParamVazioParametros(node);
        if(node.getVazio() != null)
        {
            node.getVazio().apply(this);
        }
        outAParamVazioParametros(node);
    }

    public void inAListaParametrosParametros(AListaParametrosParametros node)
    {
        defaultIn(node);
    }

    public void outAListaParametrosParametros(AListaParametrosParametros node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAListaParametrosParametros(AListaParametrosParametros node)
    {
        inAListaParametrosParametros(node);
        if(node.getParametro() != null)
        {
            node.getParametro().apply(this);
        }
        if(node.getParametroCont() != null)
        {
            node.getParametroCont().apply(this);
        }
        outAListaParametrosParametros(node);
    }

    public void inAParametro(AParametro node)
    {
        defaultIn(node);
    }

    public void outAParametro(AParametro node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParametro(AParametro node)
    {
        inAParametro(node);
        if(node.getVar() != null)
        {
            node.getVar().apply(this);
        }
        if(node.getTipoParametro() != null)
        {
            node.getTipoParametro().apply(this);
        }
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAParametro(node);
    }

    public void inATipoBaseParamTipoParametro(ATipoBaseParamTipoParametro node)
    {
        defaultIn(node);
    }

    public void outATipoBaseParamTipoParametro(ATipoBaseParamTipoParametro node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATipoBaseParamTipoParametro(ATipoBaseParamTipoParametro node)
    {
        inATipoBaseParamTipoParametro(node);
        if(node.getTipoBase() != null)
        {
            node.getTipoBase().apply(this);
        }
        outATipoBaseParamTipoParametro(node);
    }

    public void inATipoParamContTipoParametro(ATipoParamContTipoParametro node)
    {
        defaultIn(node);
    }

    public void outATipoParamContTipoParametro(ATipoParamContTipoParametro node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATipoParamContTipoParametro(ATipoParamContTipoParametro node)
    {
        inATipoParamContTipoParametro(node);
        if(node.getTipoParametro() != null)
        {
            node.getTipoParametro().apply(this);
        }
        if(node.getColcheteE() != null)
        {
            node.getColcheteE().apply(this);
        }
        if(node.getColcheteD() != null)
        {
            node.getColcheteD().apply(this);
        }
        outATipoParamContTipoParametro(node);
    }

    public void inAParametroContRecParametroCont(AParametroContRecParametroCont node)
    {
        defaultIn(node);
    }

    public void outAParametroContRecParametroCont(AParametroContRecParametroCont node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParametroContRecParametroCont(AParametroContRecParametroCont node)
    {
        inAParametroContRecParametroCont(node);
        if(node.getParametroCont() != null)
        {
            node.getParametroCont().apply(this);
        }
        if(node.getParametro() != null)
        {
            node.getParametro().apply(this);
        }
        outAParametroContRecParametroCont(node);
    }

    public void inAParametroContVazioParametroCont(AParametroContVazioParametroCont node)
    {
        defaultIn(node);
    }

    public void outAParametroContVazioParametroCont(AParametroContVazioParametroCont node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParametroContVazioParametroCont(AParametroContVazioParametroCont node)
    {
        inAParametroContVazioParametroCont(node);
        if(node.getVazio() != null)
        {
            node.getVazio().apply(this);
        }
        outAParametroContVazioParametroCont(node);
    }

    public void inAIfThenComando(AIfThenComando node)
    {
        defaultIn(node);
    }

    public void outAIfThenComando(AIfThenComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIfThenComando(AIfThenComando node)
    {
        inAIfThenComando(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getComando() != null)
        {
            node.getComando().apply(this);
        }
        outAIfThenComando(node);
    }

    public void inAIfElseComando(AIfElseComando node)
    {
        defaultIn(node);
    }

    public void outAIfElseComando(AIfElseComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIfElseComando(AIfElseComando node)
    {
        inAIfElseComando(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getComando2() != null)
        {
            node.getComando2().apply(this);
        }
        if(node.getComando() != null)
        {
            node.getComando().apply(this);
        }
        outAIfElseComando(node);
    }

    public void inAComandoWhileComando(AComandoWhileComando node)
    {
        defaultIn(node);
    }

    public void outAComandoWhileComando(AComandoWhileComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAComandoWhileComando(AComandoWhileComando node)
    {
        inAComandoWhileComando(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getComando() != null)
        {
            node.getComando().apply(this);
        }
        outAComandoWhileComando(node);
    }

    public void inAComandoVarComando(AComandoVarComando node)
    {
        defaultIn(node);
    }

    public void outAComandoVarComando(AComandoVarComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAComandoVarComando(AComandoVarComando node)
    {
        inAComandoVarComando(node);
        if(node.getVariavel() != null)
        {
            node.getVariavel().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAComandoVarComando(node);
    }

    public void inAComandoChamadaComando(AComandoChamadaComando node)
    {
        defaultIn(node);
    }

    public void outAComandoChamadaComando(AComandoChamadaComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAComandoChamadaComando(AComandoChamadaComando node)
    {
        inAComandoChamadaComando(node);
        if(node.getChamada() != null)
        {
            node.getChamada().apply(this);
        }
        outAComandoChamadaComando(node);
    }

    public void inAComandoBlocoComando(AComandoBlocoComando node)
    {
        defaultIn(node);
    }

    public void outAComandoBlocoComando(AComandoBlocoComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAComandoBlocoComando(AComandoBlocoComando node)
    {
        inAComandoBlocoComando(node);
        if(node.getBloco() != null)
        {
            node.getBloco().apply(this);
        }
        outAComandoBlocoComando(node);
    }

    public void inAIfElse2Comando2(AIfElse2Comando2 node)
    {
        defaultIn(node);
    }

    public void outAIfElse2Comando2(AIfElse2Comando2 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIfElse2Comando2(AIfElse2Comando2 node)
    {
        inAIfElse2Comando2(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getCasoTrue() != null)
        {
            node.getCasoTrue().apply(this);
        }
        if(node.getCasoFalse() != null)
        {
            node.getCasoFalse().apply(this);
        }
        outAIfElse2Comando2(node);
    }

    public void inAComandoWhile2Comando2(AComandoWhile2Comando2 node)
    {
        defaultIn(node);
    }

    public void outAComandoWhile2Comando2(AComandoWhile2Comando2 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAComandoWhile2Comando2(AComandoWhile2Comando2 node)
    {
        inAComandoWhile2Comando2(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getComando2() != null)
        {
            node.getComando2().apply(this);
        }
        outAComandoWhile2Comando2(node);
    }

    public void inAComandoVar2Comando2(AComandoVar2Comando2 node)
    {
        defaultIn(node);
    }

    public void outAComandoVar2Comando2(AComandoVar2Comando2 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAComandoVar2Comando2(AComandoVar2Comando2 node)
    {
        inAComandoVar2Comando2(node);
        if(node.getVariavel() != null)
        {
            node.getVariavel().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAComandoVar2Comando2(node);
    }

    public void inAComandoChamada2Comando2(AComandoChamada2Comando2 node)
    {
        defaultIn(node);
    }

    public void outAComandoChamada2Comando2(AComandoChamada2Comando2 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAComandoChamada2Comando2(AComandoChamada2Comando2 node)
    {
        inAComandoChamada2Comando2(node);
        if(node.getChamada() != null)
        {
            node.getChamada().apply(this);
        }
        outAComandoChamada2Comando2(node);
    }

    public void inAComandoBloco2Comando2(AComandoBloco2Comando2 node)
    {
        defaultIn(node);
    }

    public void outAComandoBloco2Comando2(AComandoBloco2Comando2 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAComandoBloco2Comando2(AComandoBloco2Comando2 node)
    {
        inAComandoBloco2Comando2(node);
        if(node.getBloco() != null)
        {
            node.getBloco().apply(this);
        }
        outAComandoBloco2Comando2(node);
    }

    public void inAElseParte2(AElseParte2 node)
    {
        defaultIn(node);
    }

    public void outAElseParte2(AElseParte2 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAElseParte2(AElseParte2 node)
    {
        inAElseParte2(node);
        if(node.getComando2() != null)
        {
            node.getComando2().apply(this);
        }
        outAElseParte2(node);
    }

    public void inABloco(ABloco node)
    {
        defaultIn(node);
    }

    public void outABloco(ABloco node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABloco(ABloco node)
    {
        inABloco(node);
        if(node.getContBloco() != null)
        {
            node.getContBloco().apply(this);
        }
        outABloco(node);
    }

    public void inAOpDecVarOpcaoBloco(AOpDecVarOpcaoBloco node)
    {
        defaultIn(node);
    }

    public void outAOpDecVarOpcaoBloco(AOpDecVarOpcaoBloco node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOpDecVarOpcaoBloco(AOpDecVarOpcaoBloco node)
    {
        inAOpDecVarOpcaoBloco(node);
        if(node.getDecVar() != null)
        {
            node.getDecVar().apply(this);
        }
        outAOpDecVarOpcaoBloco(node);
    }

    public void inAOpDecConstOpcaoBloco(AOpDecConstOpcaoBloco node)
    {
        defaultIn(node);
    }

    public void outAOpDecConstOpcaoBloco(AOpDecConstOpcaoBloco node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOpDecConstOpcaoBloco(AOpDecConstOpcaoBloco node)
    {
        inAOpDecConstOpcaoBloco(node);
        if(node.getDecConst() != null)
        {
            node.getDecConst().apply(this);
        }
        outAOpDecConstOpcaoBloco(node);
    }

    public void inAOpComandoOpcaoBloco(AOpComandoOpcaoBloco node)
    {
        defaultIn(node);
    }

    public void outAOpComandoOpcaoBloco(AOpComandoOpcaoBloco node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOpComandoOpcaoBloco(AOpComandoOpcaoBloco node)
    {
        inAOpComandoOpcaoBloco(node);
        if(node.getComando() != null)
        {
            node.getComando().apply(this);
        }
        outAOpComandoOpcaoBloco(node);
    }

    public void inAContBlocoContBloco(AContBlocoContBloco node)
    {
        defaultIn(node);
    }

    public void outAContBlocoContBloco(AContBlocoContBloco node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAContBlocoContBloco(AContBlocoContBloco node)
    {
        inAContBlocoContBloco(node);
        {
            List<POpcaoBloco> copy = new ArrayList<POpcaoBloco>(node.getOpcaoBloco());
            for(POpcaoBloco e : copy)
            {
                e.apply(this);
            }
        }
        outAContBlocoContBloco(node);
    }

    public void inAIdVariavelVariavel(AIdVariavelVariavel node)
    {
        defaultIn(node);
    }

    public void outAIdVariavelVariavel(AIdVariavelVariavel node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIdVariavelVariavel(AIdVariavelVariavel node)
    {
        inAIdVariavelVariavel(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAIdVariavelVariavel(node);
    }

    public void inAComandoVarRecVariavel(AComandoVarRecVariavel node)
    {
        defaultIn(node);
    }

    public void outAComandoVarRecVariavel(AComandoVarRecVariavel node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAComandoVarRecVariavel(AComandoVarRecVariavel node)
    {
        inAComandoVarRecVariavel(node);
        if(node.getVariavel() != null)
        {
            node.getVariavel().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAComandoVarRecVariavel(node);
    }

    public void inAOperacaoOrExp(AOperacaoOrExp node)
    {
        defaultIn(node);
    }

    public void outAOperacaoOrExp(AOperacaoOrExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOperacaoOrExp(AOperacaoOrExp node)
    {
        inAOperacaoOrExp(node);
        if(node.getLeft() != null)
        {
            node.getLeft().apply(this);
        }
        if(node.getRight() != null)
        {
            node.getRight().apply(this);
        }
        outAOperacaoOrExp(node);
    }

    public void inAOperacaoAndExp(AOperacaoAndExp node)
    {
        defaultIn(node);
    }

    public void outAOperacaoAndExp(AOperacaoAndExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOperacaoAndExp(AOperacaoAndExp node)
    {
        inAOperacaoAndExp(node);
        if(node.getLeft() != null)
        {
            node.getLeft().apply(this);
        }
        if(node.getRight() != null)
        {
            node.getRight().apply(this);
        }
        outAOperacaoAndExp(node);
    }

    public void inAOperacaoIgualExp(AOperacaoIgualExp node)
    {
        defaultIn(node);
    }

    public void outAOperacaoIgualExp(AOperacaoIgualExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOperacaoIgualExp(AOperacaoIgualExp node)
    {
        inAOperacaoIgualExp(node);
        if(node.getLeft() != null)
        {
            node.getLeft().apply(this);
        }
        if(node.getRight() != null)
        {
            node.getRight().apply(this);
        }
        outAOperacaoIgualExp(node);
    }

    public void inAOperacaoMenorExp(AOperacaoMenorExp node)
    {
        defaultIn(node);
    }

    public void outAOperacaoMenorExp(AOperacaoMenorExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOperacaoMenorExp(AOperacaoMenorExp node)
    {
        inAOperacaoMenorExp(node);
        if(node.getLeft() != null)
        {
            node.getLeft().apply(this);
        }
        if(node.getRight() != null)
        {
            node.getRight().apply(this);
        }
        outAOperacaoMenorExp(node);
    }

    public void inAOperacaoSomaExp(AOperacaoSomaExp node)
    {
        defaultIn(node);
    }

    public void outAOperacaoSomaExp(AOperacaoSomaExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOperacaoSomaExp(AOperacaoSomaExp node)
    {
        inAOperacaoSomaExp(node);
        if(node.getLeft() != null)
        {
            node.getLeft().apply(this);
        }
        if(node.getRight() != null)
        {
            node.getRight().apply(this);
        }
        outAOperacaoSomaExp(node);
    }

    public void inAOperacaoSubtracaoExp(AOperacaoSubtracaoExp node)
    {
        defaultIn(node);
    }

    public void outAOperacaoSubtracaoExp(AOperacaoSubtracaoExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOperacaoSubtracaoExp(AOperacaoSubtracaoExp node)
    {
        inAOperacaoSubtracaoExp(node);
        if(node.getLeft() != null)
        {
            node.getLeft().apply(this);
        }
        if(node.getRight() != null)
        {
            node.getRight().apply(this);
        }
        outAOperacaoSubtracaoExp(node);
    }

    public void inAOperacaoDivisaoExp(AOperacaoDivisaoExp node)
    {
        defaultIn(node);
    }

    public void outAOperacaoDivisaoExp(AOperacaoDivisaoExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOperacaoDivisaoExp(AOperacaoDivisaoExp node)
    {
        inAOperacaoDivisaoExp(node);
        if(node.getLeft() != null)
        {
            node.getLeft().apply(this);
        }
        if(node.getRight() != null)
        {
            node.getRight().apply(this);
        }
        outAOperacaoDivisaoExp(node);
    }

    public void inAOperacaoModuloExp(AOperacaoModuloExp node)
    {
        defaultIn(node);
    }

    public void outAOperacaoModuloExp(AOperacaoModuloExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOperacaoModuloExp(AOperacaoModuloExp node)
    {
        inAOperacaoModuloExp(node);
        if(node.getLeft() != null)
        {
            node.getLeft().apply(this);
        }
        if(node.getRight() != null)
        {
            node.getRight().apply(this);
        }
        outAOperacaoModuloExp(node);
    }

    public void inAOperacaoMultiplicacaoExp(AOperacaoMultiplicacaoExp node)
    {
        defaultIn(node);
    }

    public void outAOperacaoMultiplicacaoExp(AOperacaoMultiplicacaoExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOperacaoMultiplicacaoExp(AOperacaoMultiplicacaoExp node)
    {
        inAOperacaoMultiplicacaoExp(node);
        if(node.getLeft() != null)
        {
            node.getLeft().apply(this);
        }
        if(node.getRight() != null)
        {
            node.getRight().apply(this);
        }
        outAOperacaoMultiplicacaoExp(node);
    }

    public void inAOperacaoNegExp(AOperacaoNegExp node)
    {
        defaultIn(node);
    }

    public void outAOperacaoNegExp(AOperacaoNegExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOperacaoNegExp(AOperacaoNegExp node)
    {
        inAOperacaoNegExp(node);
        if(node.getNeg() != null)
        {
            node.getNeg().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAOperacaoNegExp(node);
    }

    public void inAOperacaoMenosUnariaExp(AOperacaoMenosUnariaExp node)
    {
        defaultIn(node);
    }

    public void outAOperacaoMenosUnariaExp(AOperacaoMenosUnariaExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOperacaoMenosUnariaExp(AOperacaoMenosUnariaExp node)
    {
        inAOperacaoMenosUnariaExp(node);
        if(node.getMenos() != null)
        {
            node.getMenos().apply(this);
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAOperacaoMenosUnariaExp(node);
    }

    public void inAExpNumeroInteiroExp(AExpNumeroInteiroExp node)
    {
        defaultIn(node);
    }

    public void outAExpNumeroInteiroExp(AExpNumeroInteiroExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpNumeroInteiroExp(AExpNumeroInteiroExp node)
    {
        inAExpNumeroInteiroExp(node);
        if(node.getNumeroInteiro() != null)
        {
            node.getNumeroInteiro().apply(this);
        }
        outAExpNumeroInteiroExp(node);
    }

    public void inANumeroRealExp(ANumeroRealExp node)
    {
        defaultIn(node);
    }

    public void outANumeroRealExp(ANumeroRealExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANumeroRealExp(ANumeroRealExp node)
    {
        inANumeroRealExp(node);
        if(node.getNumeroReal() != null)
        {
            node.getNumeroReal().apply(this);
        }
        outANumeroRealExp(node);
    }

    public void inATrueExp(ATrueExp node)
    {
        defaultIn(node);
    }

    public void outATrueExp(ATrueExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATrueExp(ATrueExp node)
    {
        inATrueExp(node);
        if(node.getTrue() != null)
        {
            node.getTrue().apply(this);
        }
        outATrueExp(node);
    }

    public void inAFalseExp(AFalseExp node)
    {
        defaultIn(node);
    }

    public void outAFalseExp(AFalseExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFalseExp(AFalseExp node)
    {
        inAFalseExp(node);
        if(node.getFalse() != null)
        {
            node.getFalse().apply(this);
        }
        outAFalseExp(node);
    }

    public void inAChamadaExp(AChamadaExp node)
    {
        defaultIn(node);
    }

    public void outAChamadaExp(AChamadaExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAChamadaExp(AChamadaExp node)
    {
        inAChamadaExp(node);
        if(node.getChamada() != null)
        {
            node.getChamada().apply(this);
        }
        outAChamadaExp(node);
    }

    public void inAVariavelExp(AVariavelExp node)
    {
        defaultIn(node);
    }

    public void outAVariavelExp(AVariavelExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVariavelExp(AVariavelExp node)
    {
        inAVariavelExp(node);
        if(node.getVariavel() != null)
        {
            node.getVariavel().apply(this);
        }
        outAVariavelExp(node);
    }

    public void inAIfElseExpExp(AIfElseExpExp node)
    {
        defaultIn(node);
    }

    public void outAIfElseExpExp(AIfElseExpExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIfElseExpExp(AIfElseExpExp node)
    {
        inAIfElseExpExp(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        if(node.getThenParte() != null)
        {
            node.getThenParte().apply(this);
        }
        if(node.getElseParte() != null)
        {
            node.getElseParte().apply(this);
        }
        outAIfElseExpExp(node);
    }

    public void inABlocoExpExp(ABlocoExpExp node)
    {
        defaultIn(node);
    }

    public void outABlocoExpExp(ABlocoExpExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABlocoExpExp(ABlocoExpExp node)
    {
        inABlocoExpExp(node);
        {
            List<PDecConst> copy = new ArrayList<PDecConst>(node.getDecConst());
            for(PDecConst e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outABlocoExpExp(node);
    }

    public void inARecExpParentesesRecExp(ARecExpParentesesRecExp node)
    {
        defaultIn(node);
    }

    public void outARecExpParentesesRecExp(ARecExpParentesesRecExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARecExpParentesesRecExp(ARecExpParentesesRecExp node)
    {
        inARecExpParentesesRecExp(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outARecExpParentesesRecExp(node);
    }

    public void inAThenParte(AThenParte node)
    {
        defaultIn(node);
    }

    public void outAThenParte(AThenParte node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAThenParte(AThenParte node)
    {
        inAThenParte(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAThenParte(node);
    }

    public void inAElseParte(AElseParte node)
    {
        defaultIn(node);
    }

    public void outAElseParte(AElseParte node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAElseParte(AElseParte node)
    {
        inAElseParte(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAElseParte(node);
    }

    public void inAContExp(AContExp node)
    {
        defaultIn(node);
    }

    public void outAContExp(AContExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAContExp(AContExp node)
    {
        inAContExp(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        outAContExp(node);
    }

    public void inAChamada(AChamada node)
    {
        defaultIn(node);
    }

    public void outAChamada(AChamada node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAChamada(AChamada node)
    {
        inAChamada(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        if(node.getListaExp() != null)
        {
            node.getListaExp().apply(this);
        }
        outAChamada(node);
    }

    public void inAListaVaziaListaExp(AListaVaziaListaExp node)
    {
        defaultIn(node);
    }

    public void outAListaVaziaListaExp(AListaVaziaListaExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAListaVaziaListaExp(AListaVaziaListaExp node)
    {
        inAListaVaziaListaExp(node);
        if(node.getVazio() != null)
        {
            node.getVazio().apply(this);
        }
        outAListaVaziaListaExp(node);
    }

    public void inAListaExpListaExp(AListaExpListaExp node)
    {
        defaultIn(node);
    }

    public void outAListaExpListaExp(AListaExpListaExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAListaExpListaExp(AListaExpListaExp node)
    {
        inAListaExpListaExp(node);
        if(node.getExp() != null)
        {
            node.getExp().apply(this);
        }
        {
            List<PContExp> copy = new ArrayList<PContExp>(node.getContExp());
            for(PContExp e : copy)
            {
                e.apply(this);
            }
        }
        outAListaExpListaExp(node);
    }

    public void inAIdOpcaoVar(AIdOpcaoVar node)
    {
        defaultIn(node);
    }

    public void outAIdOpcaoVar(AIdOpcaoVar node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIdOpcaoVar(AIdOpcaoVar node)
    {
        inAIdOpcaoVar(node);
        if(node.getId() != null)
        {
            node.getId().apply(this);
        }
        outAIdOpcaoVar(node);
    }

    public void inAInicializacaoOpcaoVar(AInicializacaoOpcaoVar node)
    {
        defaultIn(node);
    }

    public void outAInicializacaoOpcaoVar(AInicializacaoOpcaoVar node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAInicializacaoOpcaoVar(AInicializacaoOpcaoVar node)
    {
        inAInicializacaoOpcaoVar(node);
        if(node.getInicializacao() != null)
        {
            node.getInicializacao().apply(this);
        }
        outAInicializacaoOpcaoVar(node);
    }

    public void inAContOpcaoVar(AContOpcaoVar node)
    {
        defaultIn(node);
    }

    public void outAContOpcaoVar(AContOpcaoVar node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAContOpcaoVar(AContOpcaoVar node)
    {
        inAContOpcaoVar(node);
        if(node.getOpcaoVar() != null)
        {
            node.getOpcaoVar().apply(this);
        }
        outAContOpcaoVar(node);
    }
}
