/* This file was generated by SableCC (http://www.sablecc.org/). */

package ufs.compiladores.x.node;

import ufs.compiladores.x.analysis.*;

@SuppressWarnings("nls")
public final class AArrayComp extends PArrayComp
{
    private TId _id_;
    private PContArrayComp _contArrayComp_;

    public AArrayComp()
    {
        // Constructor
    }

    public AArrayComp(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") PContArrayComp _contArrayComp_)
    {
        // Constructor
        setId(_id_);

        setContArrayComp(_contArrayComp_);

    }

    @Override
    public Object clone()
    {
        return new AArrayComp(
            cloneNode(this._id_),
            cloneNode(this._contArrayComp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArrayComp(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public PContArrayComp getContArrayComp()
    {
        return this._contArrayComp_;
    }

    public void setContArrayComp(PContArrayComp node)
    {
        if(this._contArrayComp_ != null)
        {
            this._contArrayComp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._contArrayComp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._contArrayComp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._contArrayComp_ == child)
        {
            this._contArrayComp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._contArrayComp_ == oldChild)
        {
            setContArrayComp((PContArrayComp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
