/* This file was generated by SableCC (http://www.sablecc.org/). */

package ufs.compiladores.x.node;

import ufs.compiladores.x.analysis.*;

@SuppressWarnings("nls")
public final class AAtriIniArrayExtInicializacao extends PInicializacao
{
    private TId _id_;
    private TAtri _atri_;
    private PArrayExt _arrayExt_;

    public AAtriIniArrayExtInicializacao()
    {
        // Constructor
    }

    public AAtriIniArrayExtInicializacao(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") TAtri _atri_,
        @SuppressWarnings("hiding") PArrayExt _arrayExt_)
    {
        // Constructor
        setId(_id_);

        setAtri(_atri_);

        setArrayExt(_arrayExt_);

    }

    @Override
    public Object clone()
    {
        return new AAtriIniArrayExtInicializacao(
            cloneNode(this._id_),
            cloneNode(this._atri_),
            cloneNode(this._arrayExt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAtriIniArrayExtInicializacao(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public TAtri getAtri()
    {
        return this._atri_;
    }

    public void setAtri(TAtri node)
    {
        if(this._atri_ != null)
        {
            this._atri_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._atri_ = node;
    }

    public PArrayExt getArrayExt()
    {
        return this._arrayExt_;
    }

    public void setArrayExt(PArrayExt node)
    {
        if(this._arrayExt_ != null)
        {
            this._arrayExt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._arrayExt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._atri_)
            + toString(this._arrayExt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._atri_ == child)
        {
            this._atri_ = null;
            return;
        }

        if(this._arrayExt_ == child)
        {
            this._arrayExt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._atri_ == oldChild)
        {
            setAtri((TAtri) newChild);
            return;
        }

        if(this._arrayExt_ == oldChild)
        {
            setArrayExt((PArrayExt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
