/* This file was generated by SableCC (http://www.sablecc.org/). */

package ufs.compiladores.x.node;

import ufs.compiladores.x.analysis.*;

@SuppressWarnings("nls")
public final class ABaseContBlocoContBloco extends PContBloco
{
    private POpcaoBloco _opcaoBloco_;

    public ABaseContBlocoContBloco()
    {
        // Constructor
    }

    public ABaseContBlocoContBloco(
        @SuppressWarnings("hiding") POpcaoBloco _opcaoBloco_)
    {
        // Constructor
        setOpcaoBloco(_opcaoBloco_);

    }

    @Override
    public Object clone()
    {
        return new ABaseContBlocoContBloco(
            cloneNode(this._opcaoBloco_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABaseContBlocoContBloco(this);
    }

    public POpcaoBloco getOpcaoBloco()
    {
        return this._opcaoBloco_;
    }

    public void setOpcaoBloco(POpcaoBloco node)
    {
        if(this._opcaoBloco_ != null)
        {
            this._opcaoBloco_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opcaoBloco_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._opcaoBloco_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._opcaoBloco_ == child)
        {
            this._opcaoBloco_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._opcaoBloco_ == oldChild)
        {
            setOpcaoBloco((POpcaoBloco) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
