/* This file was generated by SableCC (http://www.sablecc.org/). */

package ufs.compiladores.x.node;

import ufs.compiladores.x.analysis.*;

@SuppressWarnings("nls")
public final class ABloco2 extends PBloco2
{
    private TChaveE _chaveE_;
    private PContBloco2 _contBloco2_;
    private TChaveD _chaveD_;

    public ABloco2()
    {
        // Constructor
    }

    public ABloco2(
        @SuppressWarnings("hiding") TChaveE _chaveE_,
        @SuppressWarnings("hiding") PContBloco2 _contBloco2_,
        @SuppressWarnings("hiding") TChaveD _chaveD_)
    {
        // Constructor
        setChaveE(_chaveE_);

        setContBloco2(_contBloco2_);

        setChaveD(_chaveD_);

    }

    @Override
    public Object clone()
    {
        return new ABloco2(
            cloneNode(this._chaveE_),
            cloneNode(this._contBloco2_),
            cloneNode(this._chaveD_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABloco2(this);
    }

    public TChaveE getChaveE()
    {
        return this._chaveE_;
    }

    public void setChaveE(TChaveE node)
    {
        if(this._chaveE_ != null)
        {
            this._chaveE_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._chaveE_ = node;
    }

    public PContBloco2 getContBloco2()
    {
        return this._contBloco2_;
    }

    public void setContBloco2(PContBloco2 node)
    {
        if(this._contBloco2_ != null)
        {
            this._contBloco2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._contBloco2_ = node;
    }

    public TChaveD getChaveD()
    {
        return this._chaveD_;
    }

    public void setChaveD(TChaveD node)
    {
        if(this._chaveD_ != null)
        {
            this._chaveD_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._chaveD_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._chaveE_)
            + toString(this._contBloco2_)
            + toString(this._chaveD_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._chaveE_ == child)
        {
            this._chaveE_ = null;
            return;
        }

        if(this._contBloco2_ == child)
        {
            this._contBloco2_ = null;
            return;
        }

        if(this._chaveD_ == child)
        {
            this._chaveD_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._chaveE_ == oldChild)
        {
            setChaveE((TChaveE) newChild);
            return;
        }

        if(this._contBloco2_ == oldChild)
        {
            setContBloco2((PContBloco2) newChild);
            return;
        }

        if(this._chaveD_ == oldChild)
        {
            setChaveD((TChaveD) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
