/* This file was generated by SableCC (http://www.sablecc.org/). */

package ufs.compiladores.x.node;

import ufs.compiladores.x.analysis.*;

@SuppressWarnings("nls")
public final class ABloco extends PBloco
{
    private PContBloco _contBloco_;

    public ABloco()
    {
        // Constructor
    }

    public ABloco(
        @SuppressWarnings("hiding") PContBloco _contBloco_)
    {
        // Constructor
        setContBloco(_contBloco_);

    }

    @Override
    public Object clone()
    {
        return new ABloco(
            cloneNode(this._contBloco_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABloco(this);
    }

    public PContBloco getContBloco()
    {
        return this._contBloco_;
    }

    public void setContBloco(PContBloco node)
    {
        if(this._contBloco_ != null)
        {
            this._contBloco_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._contBloco_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._contBloco_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._contBloco_ == child)
        {
            this._contBloco_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._contBloco_ == oldChild)
        {
            setContBloco((PContBloco) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
