/* This file was generated by SableCC (http://www.sablecc.org/). */

package ufs.compiladores.x.node;

import ufs.compiladores.x.analysis.*;

@SuppressWarnings("nls")
public final class AComandoChamada2Comando2 extends PComando2
{
    private PChamada _chamada_;

    public AComandoChamada2Comando2()
    {
        // Constructor
    }

    public AComandoChamada2Comando2(
        @SuppressWarnings("hiding") PChamada _chamada_)
    {
        // Constructor
        setChamada(_chamada_);

    }

    @Override
    public Object clone()
    {
        return new AComandoChamada2Comando2(
            cloneNode(this._chamada_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComandoChamada2Comando2(this);
    }

    public PChamada getChamada()
    {
        return this._chamada_;
    }

    public void setChamada(PChamada node)
    {
        if(this._chamada_ != null)
        {
            this._chamada_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._chamada_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._chamada_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._chamada_ == child)
        {
            this._chamada_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._chamada_ == oldChild)
        {
            setChamada((PChamada) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
