/* This file was generated by SableCC (http://www.sablecc.org/). */

package ufs.compiladores.x.node;

import ufs.compiladores.x.analysis.*;

@SuppressWarnings("nls")
public final class AComandoWhile2Comando2 extends PComando2
{
    private TWhile _while_;
    private TParE _parE_;
    private PExp _exp_;
    private TParD _parD_;
    private PComando2 _comando2_;

    public AComandoWhile2Comando2()
    {
        // Constructor
    }

    public AComandoWhile2Comando2(
        @SuppressWarnings("hiding") TWhile _while_,
        @SuppressWarnings("hiding") TParE _parE_,
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TParD _parD_,
        @SuppressWarnings("hiding") PComando2 _comando2_)
    {
        // Constructor
        setWhile(_while_);

        setParE(_parE_);

        setExp(_exp_);

        setParD(_parD_);

        setComando2(_comando2_);

    }

    @Override
    public Object clone()
    {
        return new AComandoWhile2Comando2(
            cloneNode(this._while_),
            cloneNode(this._parE_),
            cloneNode(this._exp_),
            cloneNode(this._parD_),
            cloneNode(this._comando2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComandoWhile2Comando2(this);
    }

    public TWhile getWhile()
    {
        return this._while_;
    }

    public void setWhile(TWhile node)
    {
        if(this._while_ != null)
        {
            this._while_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._while_ = node;
    }

    public TParE getParE()
    {
        return this._parE_;
    }

    public void setParE(TParE node)
    {
        if(this._parE_ != null)
        {
            this._parE_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parE_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TParD getParD()
    {
        return this._parD_;
    }

    public void setParD(TParD node)
    {
        if(this._parD_ != null)
        {
            this._parD_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parD_ = node;
    }

    public PComando2 getComando2()
    {
        return this._comando2_;
    }

    public void setComando2(PComando2 node)
    {
        if(this._comando2_ != null)
        {
            this._comando2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comando2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._while_)
            + toString(this._parE_)
            + toString(this._exp_)
            + toString(this._parD_)
            + toString(this._comando2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._while_ == child)
        {
            this._while_ = null;
            return;
        }

        if(this._parE_ == child)
        {
            this._parE_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._parD_ == child)
        {
            this._parD_ = null;
            return;
        }

        if(this._comando2_ == child)
        {
            this._comando2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._while_ == oldChild)
        {
            setWhile((TWhile) newChild);
            return;
        }

        if(this._parE_ == oldChild)
        {
            setParE((TParE) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._parD_ == oldChild)
        {
            setParD((TParD) newChild);
            return;
        }

        if(this._comando2_ == oldChild)
        {
            setComando2((PComando2) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
