/* This file was generated by SableCC (http://www.sablecc.org/). */

package ufs.compiladores.x.node;

import ufs.compiladores.x.analysis.*;

@SuppressWarnings("nls")
public final class AContInicializacao extends PContInicializacao
{
    private TVirgula _virgula_;
    private PInicializacao _inicializacao_;

    public AContInicializacao()
    {
        // Constructor
    }

    public AContInicializacao(
        @SuppressWarnings("hiding") TVirgula _virgula_,
        @SuppressWarnings("hiding") PInicializacao _inicializacao_)
    {
        // Constructor
        setVirgula(_virgula_);

        setInicializacao(_inicializacao_);

    }

    @Override
    public Object clone()
    {
        return new AContInicializacao(
            cloneNode(this._virgula_),
            cloneNode(this._inicializacao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAContInicializacao(this);
    }

    public TVirgula getVirgula()
    {
        return this._virgula_;
    }

    public void setVirgula(TVirgula node)
    {
        if(this._virgula_ != null)
        {
            this._virgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._virgula_ = node;
    }

    public PInicializacao getInicializacao()
    {
        return this._inicializacao_;
    }

    public void setInicializacao(PInicializacao node)
    {
        if(this._inicializacao_ != null)
        {
            this._inicializacao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._inicializacao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._virgula_)
            + toString(this._inicializacao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._virgula_ == child)
        {
            this._virgula_ = null;
            return;
        }

        if(this._inicializacao_ == child)
        {
            this._inicializacao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._virgula_ == oldChild)
        {
            setVirgula((TVirgula) newChild);
            return;
        }

        if(this._inicializacao_ == oldChild)
        {
            setInicializacao((PInicializacao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
