/* This file was generated by SableCC (http://www.sablecc.org/). */

package ufs.compiladores.x.node;

import ufs.compiladores.x.analysis.*;

@SuppressWarnings("nls")
public final class AContOpcaoVar extends PContOpcaoVar
{
    private TVirgula _virgula_;
    private POpcaoVar _opcaoVar_;

    public AContOpcaoVar()
    {
        // Constructor
    }

    public AContOpcaoVar(
        @SuppressWarnings("hiding") TVirgula _virgula_,
        @SuppressWarnings("hiding") POpcaoVar _opcaoVar_)
    {
        // Constructor
        setVirgula(_virgula_);

        setOpcaoVar(_opcaoVar_);

    }

    @Override
    public Object clone()
    {
        return new AContOpcaoVar(
            cloneNode(this._virgula_),
            cloneNode(this._opcaoVar_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAContOpcaoVar(this);
    }

    public TVirgula getVirgula()
    {
        return this._virgula_;
    }

    public void setVirgula(TVirgula node)
    {
        if(this._virgula_ != null)
        {
            this._virgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._virgula_ = node;
    }

    public POpcaoVar getOpcaoVar()
    {
        return this._opcaoVar_;
    }

    public void setOpcaoVar(POpcaoVar node)
    {
        if(this._opcaoVar_ != null)
        {
            this._opcaoVar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opcaoVar_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._virgula_)
            + toString(this._opcaoVar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._virgula_ == child)
        {
            this._virgula_ = null;
            return;
        }

        if(this._opcaoVar_ == child)
        {
            this._opcaoVar_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._virgula_ == oldChild)
        {
            setVirgula((TVirgula) newChild);
            return;
        }

        if(this._opcaoVar_ == oldChild)
        {
            setOpcaoVar((POpcaoVar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
