/* This file was generated by SableCC (http://www.sablecc.org/). */

package ufs.compiladores.x.node;

import ufs.compiladores.x.analysis.*;

@SuppressWarnings("nls")
public final class ADecVariavelRecPrograma extends PPrograma
{
    private PPrograma _programa_;
    private PDecVar _decVar_;

    public ADecVariavelRecPrograma()
    {
        // Constructor
    }

    public ADecVariavelRecPrograma(
        @SuppressWarnings("hiding") PPrograma _programa_,
        @SuppressWarnings("hiding") PDecVar _decVar_)
    {
        // Constructor
        setPrograma(_programa_);

        setDecVar(_decVar_);

    }

    @Override
    public Object clone()
    {
        return new ADecVariavelRecPrograma(
            cloneNode(this._programa_),
            cloneNode(this._decVar_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecVariavelRecPrograma(this);
    }

    public PPrograma getPrograma()
    {
        return this._programa_;
    }

    public void setPrograma(PPrograma node)
    {
        if(this._programa_ != null)
        {
            this._programa_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._programa_ = node;
    }

    public PDecVar getDecVar()
    {
        return this._decVar_;
    }

    public void setDecVar(PDecVar node)
    {
        if(this._decVar_ != null)
        {
            this._decVar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._decVar_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._programa_)
            + toString(this._decVar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._programa_ == child)
        {
            this._programa_ = null;
            return;
        }

        if(this._decVar_ == child)
        {
            this._decVar_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._programa_ == oldChild)
        {
            setPrograma((PPrograma) newChild);
            return;
        }

        if(this._decVar_ == oldChild)
        {
            setDecVar((PDecVar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
