/* This file was generated by SableCC (http://www.sablecc.org/). */

package ufs.compiladores.x.node;

import ufs.compiladores.x.analysis.*;

@SuppressWarnings("nls")
public final class ADecFuncaoRecPrograma extends PPrograma
{
    private PPrograma _programa_;
    private PDecFuncao _decFuncao_;

    public ADecFuncaoRecPrograma()
    {
        // Constructor
    }

    public ADecFuncaoRecPrograma(
        @SuppressWarnings("hiding") PPrograma _programa_,
        @SuppressWarnings("hiding") PDecFuncao _decFuncao_)
    {
        // Constructor
        setPrograma(_programa_);

        setDecFuncao(_decFuncao_);

    }

    @Override
    public Object clone()
    {
        return new ADecFuncaoRecPrograma(
            cloneNode(this._programa_),
            cloneNode(this._decFuncao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecFuncaoRecPrograma(this);
    }

    public PPrograma getPrograma()
    {
        return this._programa_;
    }

    public void setPrograma(PPrograma node)
    {
        if(this._programa_ != null)
        {
            this._programa_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._programa_ = node;
    }

    public PDecFuncao getDecFuncao()
    {
        return this._decFuncao_;
    }

    public void setDecFuncao(PDecFuncao node)
    {
        if(this._decFuncao_ != null)
        {
            this._decFuncao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._decFuncao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._programa_)
            + toString(this._decFuncao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._programa_ == child)
        {
            this._programa_ = null;
            return;
        }

        if(this._decFuncao_ == child)
        {
            this._decFuncao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._programa_ == oldChild)
        {
            setPrograma((PPrograma) newChild);
            return;
        }

        if(this._decFuncao_ == oldChild)
        {
            setDecFuncao((PDecFuncao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
