/* This file was generated by SableCC (http://www.sablecc.org/). */

package ufs.compiladores.x.node;

import ufs.compiladores.x.analysis.*;

@SuppressWarnings("nls")
public final class AIfExp extends PIfExp
{
    private TIf _if_;
    private TParE _parE_;
    private PExp _exp_;
    private TParD _parD_;
    private PThenParte _thenParte_;
    private PElseParte _elseParte_;

    public AIfExp()
    {
        // Constructor
    }

    public AIfExp(
        @SuppressWarnings("hiding") TIf _if_,
        @SuppressWarnings("hiding") TParE _parE_,
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TParD _parD_,
        @SuppressWarnings("hiding") PThenParte _thenParte_,
        @SuppressWarnings("hiding") PElseParte _elseParte_)
    {
        // Constructor
        setIf(_if_);

        setParE(_parE_);

        setExp(_exp_);

        setParD(_parD_);

        setThenParte(_thenParte_);

        setElseParte(_elseParte_);

    }

    @Override
    public Object clone()
    {
        return new AIfExp(
            cloneNode(this._if_),
            cloneNode(this._parE_),
            cloneNode(this._exp_),
            cloneNode(this._parD_),
            cloneNode(this._thenParte_),
            cloneNode(this._elseParte_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfExp(this);
    }

    public TIf getIf()
    {
        return this._if_;
    }

    public void setIf(TIf node)
    {
        if(this._if_ != null)
        {
            this._if_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._if_ = node;
    }

    public TParE getParE()
    {
        return this._parE_;
    }

    public void setParE(TParE node)
    {
        if(this._parE_ != null)
        {
            this._parE_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parE_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TParD getParD()
    {
        return this._parD_;
    }

    public void setParD(TParD node)
    {
        if(this._parD_ != null)
        {
            this._parD_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parD_ = node;
    }

    public PThenParte getThenParte()
    {
        return this._thenParte_;
    }

    public void setThenParte(PThenParte node)
    {
        if(this._thenParte_ != null)
        {
            this._thenParte_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._thenParte_ = node;
    }

    public PElseParte getElseParte()
    {
        return this._elseParte_;
    }

    public void setElseParte(PElseParte node)
    {
        if(this._elseParte_ != null)
        {
            this._elseParte_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._elseParte_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._if_)
            + toString(this._parE_)
            + toString(this._exp_)
            + toString(this._parD_)
            + toString(this._thenParte_)
            + toString(this._elseParte_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._if_ == child)
        {
            this._if_ = null;
            return;
        }

        if(this._parE_ == child)
        {
            this._parE_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._parD_ == child)
        {
            this._parD_ = null;
            return;
        }

        if(this._thenParte_ == child)
        {
            this._thenParte_ = null;
            return;
        }

        if(this._elseParte_ == child)
        {
            this._elseParte_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._if_ == oldChild)
        {
            setIf((TIf) newChild);
            return;
        }

        if(this._parE_ == oldChild)
        {
            setParE((TParE) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._parD_ == oldChild)
        {
            setParD((TParD) newChild);
            return;
        }

        if(this._thenParte_ == oldChild)
        {
            setThenParte((PThenParte) newChild);
            return;
        }

        if(this._elseParte_ == oldChild)
        {
            setElseParte((PElseParte) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
