/* This file was generated by SableCC (http://www.sablecc.org/). */

package ufs.compiladores.x.node;

import ufs.compiladores.x.analysis.*;

@SuppressWarnings("nls")
public final class AIfExpExp extends PExp
{
    private PIfExp _ifExp_;

    public AIfExpExp()
    {
        // Constructor
    }

    public AIfExpExp(
        @SuppressWarnings("hiding") PIfExp _ifExp_)
    {
        // Constructor
        setIfExp(_ifExp_);

    }

    @Override
    public Object clone()
    {
        return new AIfExpExp(
            cloneNode(this._ifExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfExpExp(this);
    }

    public PIfExp getIfExp()
    {
        return this._ifExp_;
    }

    public void setIfExp(PIfExp node)
    {
        if(this._ifExp_ != null)
        {
            this._ifExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ifExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ifExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ifExp_ == child)
        {
            this._ifExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ifExp_ == oldChild)
        {
            setIfExp((PIfExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
