/* This file was generated by SableCC (http://www.sablecc.org/). */

package ufs.compiladores.x.node;

import ufs.compiladores.x.analysis.*;

@SuppressWarnings("nls")
public final class AIfElse2Comando2 extends PComando2
{
    private PExp _exp_;
    private PComando2 _casoTrue_;
    private PElseParte2 _casoFalse_;

    public AIfElse2Comando2()
    {
        // Constructor
    }

    public AIfElse2Comando2(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") PComando2 _casoTrue_,
        @SuppressWarnings("hiding") PElseParte2 _casoFalse_)
    {
        // Constructor
        setExp(_exp_);

        setCasoTrue(_casoTrue_);

        setCasoFalse(_casoFalse_);

    }

    @Override
    public Object clone()
    {
        return new AIfElse2Comando2(
            cloneNode(this._exp_),
            cloneNode(this._casoTrue_),
            cloneNode(this._casoFalse_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfElse2Comando2(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public PComando2 getCasoTrue()
    {
        return this._casoTrue_;
    }

    public void setCasoTrue(PComando2 node)
    {
        if(this._casoTrue_ != null)
        {
            this._casoTrue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._casoTrue_ = node;
    }

    public PElseParte2 getCasoFalse()
    {
        return this._casoFalse_;
    }

    public void setCasoFalse(PElseParte2 node)
    {
        if(this._casoFalse_ != null)
        {
            this._casoFalse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._casoFalse_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._casoTrue_)
            + toString(this._casoFalse_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._casoTrue_ == child)
        {
            this._casoTrue_ = null;
            return;
        }

        if(this._casoFalse_ == child)
        {
            this._casoFalse_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._casoTrue_ == oldChild)
        {
            setCasoTrue((PComando2) newChild);
            return;
        }

        if(this._casoFalse_ == oldChild)
        {
            setCasoFalse((PElseParte2) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
