/* This file was generated by SableCC (http://www.sablecc.org/). */

package ufs.compiladores.x.node;

import ufs.compiladores.x.analysis.*;

@SuppressWarnings("nls")
public final class AOperacaoMenosUnariaOperacaoUnaria extends POperacaoUnaria
{
    private TMenos _menos_;
    private POperacaoUnaria _operacaoUnaria_;

    public AOperacaoMenosUnariaOperacaoUnaria()
    {
        // Constructor
    }

    public AOperacaoMenosUnariaOperacaoUnaria(
        @SuppressWarnings("hiding") TMenos _menos_,
        @SuppressWarnings("hiding") POperacaoUnaria _operacaoUnaria_)
    {
        // Constructor
        setMenos(_menos_);

        setOperacaoUnaria(_operacaoUnaria_);

    }

    @Override
    public Object clone()
    {
        return new AOperacaoMenosUnariaOperacaoUnaria(
            cloneNode(this._menos_),
            cloneNode(this._operacaoUnaria_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOperacaoMenosUnariaOperacaoUnaria(this);
    }

    public TMenos getMenos()
    {
        return this._menos_;
    }

    public void setMenos(TMenos node)
    {
        if(this._menos_ != null)
        {
            this._menos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._menos_ = node;
    }

    public POperacaoUnaria getOperacaoUnaria()
    {
        return this._operacaoUnaria_;
    }

    public void setOperacaoUnaria(POperacaoUnaria node)
    {
        if(this._operacaoUnaria_ != null)
        {
            this._operacaoUnaria_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._operacaoUnaria_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._menos_)
            + toString(this._operacaoUnaria_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._menos_ == child)
        {
            this._menos_ = null;
            return;
        }

        if(this._operacaoUnaria_ == child)
        {
            this._operacaoUnaria_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._menos_ == oldChild)
        {
            setMenos((TMenos) newChild);
            return;
        }

        if(this._operacaoUnaria_ == oldChild)
        {
            setOperacaoUnaria((POperacaoUnaria) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
