/* This file was generated by SableCC (http://www.sablecc.org/). */

package ufs.compiladores.x.node;

import ufs.compiladores.x.analysis.*;

@SuppressWarnings("nls")
public final class AOperacaoSomaOperacaoSomaSub extends POperacaoSomaSub
{
    private POperacaoSomaSub _operacaoSomaSub_;
    private TMais _mais_;
    private POperacaoDivMulMod _operacaoDivMulMod_;

    public AOperacaoSomaOperacaoSomaSub()
    {
        // Constructor
    }

    public AOperacaoSomaOperacaoSomaSub(
        @SuppressWarnings("hiding") POperacaoSomaSub _operacaoSomaSub_,
        @SuppressWarnings("hiding") TMais _mais_,
        @SuppressWarnings("hiding") POperacaoDivMulMod _operacaoDivMulMod_)
    {
        // Constructor
        setOperacaoSomaSub(_operacaoSomaSub_);

        setMais(_mais_);

        setOperacaoDivMulMod(_operacaoDivMulMod_);

    }

    @Override
    public Object clone()
    {
        return new AOperacaoSomaOperacaoSomaSub(
            cloneNode(this._operacaoSomaSub_),
            cloneNode(this._mais_),
            cloneNode(this._operacaoDivMulMod_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOperacaoSomaOperacaoSomaSub(this);
    }

    public POperacaoSomaSub getOperacaoSomaSub()
    {
        return this._operacaoSomaSub_;
    }

    public void setOperacaoSomaSub(POperacaoSomaSub node)
    {
        if(this._operacaoSomaSub_ != null)
        {
            this._operacaoSomaSub_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._operacaoSomaSub_ = node;
    }

    public TMais getMais()
    {
        return this._mais_;
    }

    public void setMais(TMais node)
    {
        if(this._mais_ != null)
        {
            this._mais_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mais_ = node;
    }

    public POperacaoDivMulMod getOperacaoDivMulMod()
    {
        return this._operacaoDivMulMod_;
    }

    public void setOperacaoDivMulMod(POperacaoDivMulMod node)
    {
        if(this._operacaoDivMulMod_ != null)
        {
            this._operacaoDivMulMod_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._operacaoDivMulMod_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._operacaoSomaSub_)
            + toString(this._mais_)
            + toString(this._operacaoDivMulMod_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._operacaoSomaSub_ == child)
        {
            this._operacaoSomaSub_ = null;
            return;
        }

        if(this._mais_ == child)
        {
            this._mais_ = null;
            return;
        }

        if(this._operacaoDivMulMod_ == child)
        {
            this._operacaoDivMulMod_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._operacaoSomaSub_ == oldChild)
        {
            setOperacaoSomaSub((POperacaoSomaSub) newChild);
            return;
        }

        if(this._mais_ == oldChild)
        {
            setMais((TMais) newChild);
            return;
        }

        if(this._operacaoDivMulMod_ == oldChild)
        {
            setOperacaoDivMulMod((POperacaoDivMulMod) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
