/* This file was generated by SableCC (http://www.sablecc.org/). */

package ufs.compiladores.x.node;

import ufs.compiladores.x.analysis.*;

@SuppressWarnings("nls")
public final class AParaOperacaoUnariaOperacaoDivMulMod extends POperacaoDivMulMod
{
    private POperacaoUnaria _operacaoUnaria_;

    public AParaOperacaoUnariaOperacaoDivMulMod()
    {
        // Constructor
    }

    public AParaOperacaoUnariaOperacaoDivMulMod(
        @SuppressWarnings("hiding") POperacaoUnaria _operacaoUnaria_)
    {
        // Constructor
        setOperacaoUnaria(_operacaoUnaria_);

    }

    @Override
    public Object clone()
    {
        return new AParaOperacaoUnariaOperacaoDivMulMod(
            cloneNode(this._operacaoUnaria_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParaOperacaoUnariaOperacaoDivMulMod(this);
    }

    public POperacaoUnaria getOperacaoUnaria()
    {
        return this._operacaoUnaria_;
    }

    public void setOperacaoUnaria(POperacaoUnaria node)
    {
        if(this._operacaoUnaria_ != null)
        {
            this._operacaoUnaria_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._operacaoUnaria_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._operacaoUnaria_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._operacaoUnaria_ == child)
        {
            this._operacaoUnaria_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._operacaoUnaria_ == oldChild)
        {
            setOperacaoUnaria((POperacaoUnaria) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
