/* This file was generated by SableCC (http://www.sablecc.org/). */

package ufs.compiladores.x.node;

import ufs.compiladores.x.analysis.*;

@SuppressWarnings("nls")
public final class AParaOperacaoDivMulModOperacaoSomaSub extends POperacaoSomaSub
{
    private POperacaoDivMulMod _operacaoDivMulMod_;

    public AParaOperacaoDivMulModOperacaoSomaSub()
    {
        // Constructor
    }

    public AParaOperacaoDivMulModOperacaoSomaSub(
        @SuppressWarnings("hiding") POperacaoDivMulMod _operacaoDivMulMod_)
    {
        // Constructor
        setOperacaoDivMulMod(_operacaoDivMulMod_);

    }

    @Override
    public Object clone()
    {
        return new AParaOperacaoDivMulModOperacaoSomaSub(
            cloneNode(this._operacaoDivMulMod_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParaOperacaoDivMulModOperacaoSomaSub(this);
    }

    public POperacaoDivMulMod getOperacaoDivMulMod()
    {
        return this._operacaoDivMulMod_;
    }

    public void setOperacaoDivMulMod(POperacaoDivMulMod node)
    {
        if(this._operacaoDivMulMod_ != null)
        {
            this._operacaoDivMulMod_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._operacaoDivMulMod_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._operacaoDivMulMod_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._operacaoDivMulMod_ == child)
        {
            this._operacaoDivMulMod_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._operacaoDivMulMod_ == oldChild)
        {
            setOperacaoDivMulMod((POperacaoDivMulMod) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
