/* This file was generated by SableCC (http://www.sablecc.org/). */

package ufs.compiladores.x.node;

import ufs.compiladores.x.analysis.*;

@SuppressWarnings("nls")
public final class AParametros extends PParametros
{
    private PParametro _parametro_;
    private PParametroCont _parametroCont_;

    public AParametros()
    {
        // Constructor
    }

    public AParametros(
        @SuppressWarnings("hiding") PParametro _parametro_,
        @SuppressWarnings("hiding") PParametroCont _parametroCont_)
    {
        // Constructor
        setParametro(_parametro_);

        setParametroCont(_parametroCont_);

    }

    @Override
    public Object clone()
    {
        return new AParametros(
            cloneNode(this._parametro_),
            cloneNode(this._parametroCont_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParametros(this);
    }

    public PParametro getParametro()
    {
        return this._parametro_;
    }

    public void setParametro(PParametro node)
    {
        if(this._parametro_ != null)
        {
            this._parametro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parametro_ = node;
    }

    public PParametroCont getParametroCont()
    {
        return this._parametroCont_;
    }

    public void setParametroCont(PParametroCont node)
    {
        if(this._parametroCont_ != null)
        {
            this._parametroCont_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parametroCont_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._parametro_)
            + toString(this._parametroCont_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._parametro_ == child)
        {
            this._parametro_ = null;
            return;
        }

        if(this._parametroCont_ == child)
        {
            this._parametroCont_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._parametro_ == oldChild)
        {
            setParametro((PParametro) newChild);
            return;
        }

        if(this._parametroCont_ == oldChild)
        {
            setParametroCont((PParametroCont) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
