/* This file was generated by SableCC (http://www.sablecc.org/). */

package ufs.compiladores.x.node;

import ufs.compiladores.x.analysis.*;

@SuppressWarnings("nls")
public final class AVazioVazio extends PVazio
{

    public AVazioVazio()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new AVazioVazio();
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVazioVazio(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
