/* This file was generated by SableCC (http://www.sablecc.org/). */

package ufs.compiladores.x.parser;

import ufs.compiladores.x.lexer.*;
import ufs.compiladores.x.node.*;
import ufs.compiladores.x.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

@SuppressWarnings("nls")
public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList<Object> nodeList;

    private final Lexer lexer;
    private final ListIterator<Object> stack = new LinkedList<Object>().listIterator();
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(@SuppressWarnings("hiding") Lexer lexer)
    {
        this.lexer = lexer;
    }

    protected void filter() throws ParserException, LexerException, IOException
    {
        // Empty body
    }

    private void push(int numstate, ArrayList<Object> listNode, boolean hidden) throws ParserException, LexerException, IOException
    {
        this.nodeList = listNode;

        if(!hidden)
        {
            filter();
        }

        if(!this.stack.hasNext())
        {
            this.stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) this.stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            // int middle = (low + high) / 2;
            int middle = (low + high) >>> 1;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private int state()
    {
        State s = (State) this.stack.previous();
        this.stack.next();
        return s.state;
    }

    private ArrayList<Object> pop()
    {
        return ((State) this.stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        this.converter.index = -1;
        token.apply(this.converter);
        return this.converter.index;
    }

    @SuppressWarnings("unchecked")
    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null, true);
        List<Node> ign = null;
        while(true)
        {
            while(index(this.lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new LinkedList<Node>();
                }

                ign.add(this.lexer.next());
            }

            if(ign != null)
            {
                this.ignoredTokens.setIn(this.lexer.peek(), ign);
                ign = null;
            }

            this.last_pos = this.lexer.peek().getPos();
            this.last_line = this.lexer.peek().getLine();
            this.last_token = this.lexer.peek();

            int index = index(this.lexer.peek());
            this.action[0] = Parser.actionTable[state()][0][1];
            this.action[1] = Parser.actionTable[state()][0][2];

            int low = 1;
            int high = Parser.actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < Parser.actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > Parser.actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    this.action[0] = Parser.actionTable[state()][middle][1];
                    this.action[1] = Parser.actionTable[state()][middle][2];
                    break;
                }
            }

            switch(this.action[0])
            {
                case SHIFT:
		    {
		        ArrayList<Object> list = new ArrayList<Object>();
		        list.add(this.lexer.next());
                        push(this.action[1], list, false);
                    }
		    break;
                case REDUCE:
                    {
                        int reduction = this.action[1];
                        if(reduction < 500) reduce_0(reduction);
                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) this.lexer.next();
                        PInicioPrograma node1 = (PInicioPrograma) pop().get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(this.last_token,
                        "[" + this.last_line + "," + this.last_pos + "] " +
                        Parser.errorMessages[Parser.errors[this.action[1]]]);
            }
        }
    }

    private void reduce_0(int reduction) throws IOException, LexerException, ParserException
    {
        switch(reduction)
        {
            case 0: /* reduce AInicioPrograma */
            {
                ArrayList<Object> list = new0();
                push(goTo(0), list, false);
            }
            break;
            case 1: /* reduce ADecVariavelRecPrograma */
            {
                ArrayList<Object> list = new1();
                push(goTo(1), list, false);
            }
            break;
            case 2: /* reduce ADecVariavelUnicoPrograma */
            {
                ArrayList<Object> list = new2();
                push(goTo(1), list, false);
            }
            break;
            case 3: /* reduce ADecConstanteRecPrograma */
            {
                ArrayList<Object> list = new3();
                push(goTo(1), list, false);
            }
            break;
            case 4: /* reduce ADecConstanteUnicoPrograma */
            {
                ArrayList<Object> list = new4();
                push(goTo(1), list, false);
            }
            break;
            case 5: /* reduce ADecProcedimentoRecPrograma */
            {
                ArrayList<Object> list = new5();
                push(goTo(1), list, false);
            }
            break;
            case 6: /* reduce ADecProcedimentoUnicoPrograma */
            {
                ArrayList<Object> list = new6();
                push(goTo(1), list, false);
            }
            break;
            case 7: /* reduce ADecFuncaoRecPrograma */
            {
                ArrayList<Object> list = new7();
                push(goTo(1), list, false);
            }
            break;
            case 8: /* reduce ADecFuncaoUnicoPrograma */
            {
                ArrayList<Object> list = new8();
                push(goTo(1), list, false);
            }
            break;
            case 9: /* reduce AAdecvar1DecVar */
            {
                ArrayList<Object> list = new9();
                push(goTo(2), list, false);
            }
            break;
            case 10: /* reduce AAdecvar2DecVar */
            {
                ArrayList<Object> list = new10();
                push(goTo(2), list, false);
            }
            break;
            case 11: /* reduce AAdecconst1DecConst */
            {
                ArrayList<Object> list = new11();
                push(goTo(3), list, false);
            }
            break;
            case 12: /* reduce AAdecconst2DecConst */
            {
                ArrayList<Object> list = new12();
                push(goTo(3), list, false);
            }
            break;
            case 13: /* reduce AInicializacao */
            {
                ArrayList<Object> list = new13();
                push(goTo(4), list, false);
            }
            break;
            case 14: /* reduce AContInicializacao */
            {
                ArrayList<Object> list = new14();
                push(goTo(5), list, false);
            }
            break;
            case 15: /* reduce AAarrayext1ArrayExt */
            {
                ArrayList<Object> list = new15();
                push(goTo(6), list, false);
            }
            break;
            case 16: /* reduce AAarrayext2ArrayExt */
            {
                ArrayList<Object> list = new16();
                push(goTo(6), list, false);
            }
            break;
            case 17: /* reduce AArrayComp */
            {
                ArrayList<Object> list = new17();
                push(goTo(7), list, false);
            }
            break;
            case 18: /* reduce AArrayCompEscolhaContArrayComp */
            {
                ArrayList<Object> list = new18();
                push(goTo(8), list, false);
            }
            break;
            case 19: /* reduce AExpEscolhaContArrayComp */
            {
                ArrayList<Object> list = new19();
                push(goTo(8), list, false);
            }
            break;
            case 20: /* reduce ATipoBaseTipo */
            {
                ArrayList<Object> list = new20();
                push(goTo(9), list, false);
            }
            break;
            case 21: /* reduce ATipoCompostoTipo */
            {
                ArrayList<Object> list = new21();
                push(goTo(9), list, false);
            }
            break;
            case 22: /* reduce AIntTipoBase */
            {
                ArrayList<Object> list = new22();
                push(goTo(10), list, false);
            }
            break;
            case 23: /* reduce ABoolTipoBase */
            {
                ArrayList<Object> list = new23();
                push(goTo(10), list, false);
            }
            break;
            case 24: /* reduce ARealTipoBase */
            {
                ArrayList<Object> list = new24();
                push(goTo(10), list, false);
            }
            break;
            case 25: /* reduce ADecProcedimento */
            {
                ArrayList<Object> list = new25();
                push(goTo(11), list, false);
            }
            break;
            case 26: /* reduce ADecFuncao */
            {
                ArrayList<Object> list = new26();
                push(goTo(12), list, false);
            }
            break;
            case 27: /* reduce AVazioParametros */
            {
                ArrayList<Object> list = new27();
                push(goTo(13), list, false);
            }
            break;
            case 28: /* reduce AAparametros1Parametros */
            {
                ArrayList<Object> list = new28();
                push(goTo(13), list, false);
            }
            break;
            case 29: /* reduce AAparametros2Parametros */
            {
                ArrayList<Object> list = new29();
                push(goTo(13), list, false);
            }
            break;
            case 30: /* reduce AAparametro1Parametro */
            {
                ArrayList<Object> list = new30();
                push(goTo(14), list, false);
            }
            break;
            case 31: /* reduce AAparametro2Parametro */
            {
                ArrayList<Object> list = new31();
                push(goTo(14), list, false);
            }
            break;
            case 32: /* reduce ATipoBaseParamTipoParametro */
            {
                ArrayList<Object> list = new32();
                push(goTo(15), list, false);
            }
            break;
            case 33: /* reduce ATipoParamContTipoParametro */
            {
                ArrayList<Object> list = new33();
                push(goTo(15), list, false);
            }
            break;
            case 34: /* reduce AParametroCont */
            {
                ArrayList<Object> list = new34();
                push(goTo(16), list, false);
            }
            break;
            case 35: /* reduce APorEnquantoVazioComando */
            {
                ArrayList<Object> list = new35();
                push(goTo(17), list, false);
            }
            break;
            case 36: /* reduce AIdOpcaoVar */
            {
                ArrayList<Object> list = new36();
                push(goTo(18), list, false);
            }
            break;
            case 37: /* reduce AInicializacaoOpcaoVar */
            {
                ArrayList<Object> list = new37();
                push(goTo(18), list, false);
            }
            break;
            case 38: /* reduce AContOpcaoVar */
            {
                ArrayList<Object> list = new38();
                push(goTo(19), list, false);
            }
            break;
            case 39: /* reduce AVazioExp */
            {
                ArrayList<Object> list = new39();
                push(goTo(20), list, false);
            }
            break;
            case 40: /* reduce AContExp */
            {
                ArrayList<Object> list = new40();
                push(goTo(21), list, false);
            }
            break;
            case 41: /* reduce ATerminal$ContOpcaoVar */
            {
                ArrayList<Object> list = new41();
                push(goTo(22), list, true);
            }
            break;
            case 42: /* reduce ANonTerminal$ContOpcaoVar */
            {
                ArrayList<Object> list = new42();
                push(goTo(22), list, true);
            }
            break;
            case 43: /* reduce ATerminal$ContInicializacao */
            {
                ArrayList<Object> list = new43();
                push(goTo(23), list, true);
            }
            break;
            case 44: /* reduce ANonTerminal$ContInicializacao */
            {
                ArrayList<Object> list = new44();
                push(goTo(23), list, true);
            }
            break;
            case 45: /* reduce ATerminal$ContExp */
            {
                ArrayList<Object> list = new45();
                push(goTo(24), list, true);
            }
            break;
            case 46: /* reduce ANonTerminal$ContExp */
            {
                ArrayList<Object> list = new46();
                push(goTo(24), list, true);
            }
            break;
            case 47: /* reduce ATerminal$ParametroCont */
            {
                ArrayList<Object> list = new47();
                push(goTo(25), list, true);
            }
            break;
            case 48: /* reduce ANonTerminal$ParametroCont */
            {
                ArrayList<Object> list = new48();
                push(goTo(25), list, true);
            }
            break;
        }
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new0() /* reduce AInicioPrograma */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PInicioPrograma pinicioprogramaNode1;
        {
            // Block
        PPrograma pprogramaNode2;
        pprogramaNode2 = (PPrograma)nodeArrayList1.get(0);

        pinicioprogramaNode1 = new AInicioPrograma(pprogramaNode2);
        }
	nodeList.add(pinicioprogramaNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new1() /* reduce ADecVariavelRecPrograma */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PPrograma pprogramaNode1;
        {
            // Block
        PPrograma pprogramaNode2;
        PDecVar pdecvarNode3;
        pprogramaNode2 = (PPrograma)nodeArrayList1.get(0);
        pdecvarNode3 = (PDecVar)nodeArrayList2.get(0);

        pprogramaNode1 = new ADecVariavelRecPrograma(pprogramaNode2, pdecvarNode3);
        }
	nodeList.add(pprogramaNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new2() /* reduce ADecVariavelUnicoPrograma */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PPrograma pprogramaNode1;
        {
            // Block
        PDecVar pdecvarNode2;
        pdecvarNode2 = (PDecVar)nodeArrayList1.get(0);

        pprogramaNode1 = new ADecVariavelUnicoPrograma(pdecvarNode2);
        }
	nodeList.add(pprogramaNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new3() /* reduce ADecConstanteRecPrograma */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PPrograma pprogramaNode1;
        {
            // Block
        PPrograma pprogramaNode2;
        PDecConst pdecconstNode3;
        pprogramaNode2 = (PPrograma)nodeArrayList1.get(0);
        pdecconstNode3 = (PDecConst)nodeArrayList2.get(0);

        pprogramaNode1 = new ADecConstanteRecPrograma(pprogramaNode2, pdecconstNode3);
        }
	nodeList.add(pprogramaNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new4() /* reduce ADecConstanteUnicoPrograma */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PPrograma pprogramaNode1;
        {
            // Block
        PDecConst pdecconstNode2;
        pdecconstNode2 = (PDecConst)nodeArrayList1.get(0);

        pprogramaNode1 = new ADecConstanteUnicoPrograma(pdecconstNode2);
        }
	nodeList.add(pprogramaNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new5() /* reduce ADecProcedimentoRecPrograma */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PPrograma pprogramaNode1;
        {
            // Block
        PPrograma pprogramaNode2;
        PDecProcedimento pdecprocedimentoNode3;
        pprogramaNode2 = (PPrograma)nodeArrayList1.get(0);
        pdecprocedimentoNode3 = (PDecProcedimento)nodeArrayList2.get(0);

        pprogramaNode1 = new ADecProcedimentoRecPrograma(pprogramaNode2, pdecprocedimentoNode3);
        }
	nodeList.add(pprogramaNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new6() /* reduce ADecProcedimentoUnicoPrograma */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PPrograma pprogramaNode1;
        {
            // Block
        PDecProcedimento pdecprocedimentoNode2;
        pdecprocedimentoNode2 = (PDecProcedimento)nodeArrayList1.get(0);

        pprogramaNode1 = new ADecProcedimentoUnicoPrograma(pdecprocedimentoNode2);
        }
	nodeList.add(pprogramaNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new7() /* reduce ADecFuncaoRecPrograma */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PPrograma pprogramaNode1;
        {
            // Block
        PPrograma pprogramaNode2;
        PDecFuncao pdecfuncaoNode3;
        pprogramaNode2 = (PPrograma)nodeArrayList1.get(0);
        pdecfuncaoNode3 = (PDecFuncao)nodeArrayList2.get(0);

        pprogramaNode1 = new ADecFuncaoRecPrograma(pprogramaNode2, pdecfuncaoNode3);
        }
	nodeList.add(pprogramaNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new8() /* reduce ADecFuncaoUnicoPrograma */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PPrograma pprogramaNode1;
        {
            // Block
        PDecFuncao pdecfuncaoNode2;
        pdecfuncaoNode2 = (PDecFuncao)nodeArrayList1.get(0);

        pprogramaNode1 = new ADecFuncaoUnicoPrograma(pdecfuncaoNode2);
        }
	nodeList.add(pprogramaNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new9() /* reduce AAdecvar1DecVar */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecVar pdecvarNode1;
        {
            // Block
        TVar tvarNode2;
        PTipo ptipoNode3;
        POpcaoVar popcaovarNode4;
        LinkedList<Object> listNode5 = new LinkedList<Object>();
        TPontoVirgula tpontovirgulaNode6;
        tvarNode2 = (TVar)nodeArrayList1.get(0);
        ptipoNode3 = (PTipo)nodeArrayList2.get(0);
        popcaovarNode4 = (POpcaoVar)nodeArrayList3.get(0);
        {
            // Block
        }
        tpontovirgulaNode6 = (TPontoVirgula)nodeArrayList4.get(0);

        pdecvarNode1 = new ADecVar(tvarNode2, ptipoNode3, popcaovarNode4, listNode5, tpontovirgulaNode6);
        }
	nodeList.add(pdecvarNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new10() /* reduce AAdecvar2DecVar */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecVar pdecvarNode1;
        {
            // Block
        TVar tvarNode2;
        PTipo ptipoNode3;
        POpcaoVar popcaovarNode4;
        LinkedList<Object> listNode6 = new LinkedList<Object>();
        TPontoVirgula tpontovirgulaNode7;
        tvarNode2 = (TVar)nodeArrayList1.get(0);
        ptipoNode3 = (PTipo)nodeArrayList2.get(0);
        popcaovarNode4 = (POpcaoVar)nodeArrayList3.get(0);
        {
            // Block
        LinkedList<Object> listNode5 = new LinkedList<Object>();
        listNode5 = (LinkedList)nodeArrayList4.get(0);
	if(listNode5 != null)
	{
	  listNode6.addAll(listNode5);
	}
        }
        tpontovirgulaNode7 = (TPontoVirgula)nodeArrayList5.get(0);

        pdecvarNode1 = new ADecVar(tvarNode2, ptipoNode3, popcaovarNode4, listNode6, tpontovirgulaNode7);
        }
	nodeList.add(pdecvarNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new11() /* reduce AAdecconst1DecConst */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecConst pdecconstNode1;
        {
            // Block
        TCons tconsNode2;
        PTipo ptipoNode3;
        PInicializacao pinicializacaoNode4;
        LinkedList<Object> listNode5 = new LinkedList<Object>();
        TPontoVirgula tpontovirgulaNode6;
        tconsNode2 = (TCons)nodeArrayList1.get(0);
        ptipoNode3 = (PTipo)nodeArrayList2.get(0);
        pinicializacaoNode4 = (PInicializacao)nodeArrayList3.get(0);
        {
            // Block
        }
        tpontovirgulaNode6 = (TPontoVirgula)nodeArrayList4.get(0);

        pdecconstNode1 = new ADecConst(tconsNode2, ptipoNode3, pinicializacaoNode4, listNode5, tpontovirgulaNode6);
        }
	nodeList.add(pdecconstNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new12() /* reduce AAdecconst2DecConst */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecConst pdecconstNode1;
        {
            // Block
        TCons tconsNode2;
        PTipo ptipoNode3;
        PInicializacao pinicializacaoNode4;
        LinkedList<Object> listNode6 = new LinkedList<Object>();
        TPontoVirgula tpontovirgulaNode7;
        tconsNode2 = (TCons)nodeArrayList1.get(0);
        ptipoNode3 = (PTipo)nodeArrayList2.get(0);
        pinicializacaoNode4 = (PInicializacao)nodeArrayList3.get(0);
        {
            // Block
        LinkedList<Object> listNode5 = new LinkedList<Object>();
        listNode5 = (LinkedList)nodeArrayList4.get(0);
	if(listNode5 != null)
	{
	  listNode6.addAll(listNode5);
	}
        }
        tpontovirgulaNode7 = (TPontoVirgula)nodeArrayList5.get(0);

        pdecconstNode1 = new ADecConst(tconsNode2, ptipoNode3, pinicializacaoNode4, listNode6, tpontovirgulaNode7);
        }
	nodeList.add(pdecconstNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new13() /* reduce AInicializacao */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PInicializacao pinicializacaoNode1;
        {
            // Block
        TId tidNode2;
        TAtri tatriNode3;
        PExp pexpNode4;
        tidNode2 = (TId)nodeArrayList1.get(0);
        tatriNode3 = (TAtri)nodeArrayList2.get(0);
        pexpNode4 = (PExp)nodeArrayList3.get(0);

        pinicializacaoNode1 = new AInicializacao(tidNode2, tatriNode3, pexpNode4);
        }
	nodeList.add(pinicializacaoNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new14() /* reduce AContInicializacao */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PContInicializacao pcontinicializacaoNode1;
        {
            // Block
        TVirgula tvirgulaNode2;
        PInicializacao pinicializacaoNode3;
        tvirgulaNode2 = (TVirgula)nodeArrayList1.get(0);
        pinicializacaoNode3 = (PInicializacao)nodeArrayList2.get(0);

        pcontinicializacaoNode1 = new AContInicializacao(tvirgulaNode2, pinicializacaoNode3);
        }
	nodeList.add(pcontinicializacaoNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new15() /* reduce AAarrayext1ArrayExt */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PArrayExt parrayextNode1;
        {
            // Block
        TColcheteE tcolcheteeNode2;
        PExp pexpNode3;
        LinkedList<Object> listNode4 = new LinkedList<Object>();
        TColcheteD tcolchetedNode5;
        tcolcheteeNode2 = (TColcheteE)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList2.get(0);
        {
            // Block
        }
        tcolchetedNode5 = (TColcheteD)nodeArrayList3.get(0);

        parrayextNode1 = new AArrayExt(tcolcheteeNode2, pexpNode3, listNode4, tcolchetedNode5);
        }
	nodeList.add(parrayextNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new16() /* reduce AAarrayext2ArrayExt */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PArrayExt parrayextNode1;
        {
            // Block
        TColcheteE tcolcheteeNode2;
        PExp pexpNode3;
        LinkedList<Object> listNode5 = new LinkedList<Object>();
        TColcheteD tcolchetedNode6;
        tcolcheteeNode2 = (TColcheteE)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList2.get(0);
        {
            // Block
        LinkedList<Object> listNode4 = new LinkedList<Object>();
        listNode4 = (LinkedList)nodeArrayList3.get(0);
	if(listNode4 != null)
	{
	  listNode5.addAll(listNode4);
	}
        }
        tcolchetedNode6 = (TColcheteD)nodeArrayList4.get(0);

        parrayextNode1 = new AArrayExt(tcolcheteeNode2, pexpNode3, listNode5, tcolchetedNode6);
        }
	nodeList.add(parrayextNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new17() /* reduce AArrayComp */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PArrayComp parraycompNode1;
        {
            // Block
        TColcheteE tcolcheteeNode2;
        TId tidNode3;
        TPipe tpipeNode4;
        PContArrayComp pcontarraycompNode5;
        TColcheteD tcolchetedNode6;
        tcolcheteeNode2 = (TColcheteE)nodeArrayList1.get(0);
        tidNode3 = (TId)nodeArrayList2.get(0);
        tpipeNode4 = (TPipe)nodeArrayList3.get(0);
        pcontarraycompNode5 = (PContArrayComp)nodeArrayList4.get(0);
        tcolchetedNode6 = (TColcheteD)nodeArrayList5.get(0);

        parraycompNode1 = new AArrayComp(tcolcheteeNode2, tidNode3, tpipeNode4, pcontarraycompNode5, tcolchetedNode6);
        }
	nodeList.add(parraycompNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new18() /* reduce AArrayCompEscolhaContArrayComp */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PContArrayComp pcontarraycompNode1;
        {
            // Block
        PArrayComp parraycompNode2;
        parraycompNode2 = (PArrayComp)nodeArrayList1.get(0);

        pcontarraycompNode1 = new AArrayCompEscolhaContArrayComp(parraycompNode2);
        }
	nodeList.add(pcontarraycompNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new19() /* reduce AExpEscolhaContArrayComp */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PContArrayComp pcontarraycompNode1;
        {
            // Block
        PExp pexpNode2;
        pexpNode2 = (PExp)nodeArrayList1.get(0);

        pcontarraycompNode1 = new AExpEscolhaContArrayComp(pexpNode2);
        }
	nodeList.add(pcontarraycompNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new20() /* reduce ATipoBaseTipo */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTipo ptipoNode1;
        {
            // Block
        PTipoBase ptipobaseNode2;
        ptipobaseNode2 = (PTipoBase)nodeArrayList1.get(0);

        ptipoNode1 = new ATipoBaseTipo(ptipobaseNode2);
        }
	nodeList.add(ptipoNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new21() /* reduce ATipoCompostoTipo */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTipo ptipoNode1;
        {
            // Block
        PTipo ptipoNode2;
        TColcheteE tcolcheteeNode3;
        PExp pexpNode4;
        TColcheteD tcolchetedNode5;
        ptipoNode2 = (PTipo)nodeArrayList1.get(0);
        tcolcheteeNode3 = (TColcheteE)nodeArrayList2.get(0);
        pexpNode4 = (PExp)nodeArrayList3.get(0);
        tcolchetedNode5 = (TColcheteD)nodeArrayList4.get(0);

        ptipoNode1 = new ATipoCompostoTipo(ptipoNode2, tcolcheteeNode3, pexpNode4, tcolchetedNode5);
        }
	nodeList.add(ptipoNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new22() /* reduce AIntTipoBase */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTipoBase ptipobaseNode1;
        {
            // Block
        TInt tintNode2;
        tintNode2 = (TInt)nodeArrayList1.get(0);

        ptipobaseNode1 = new AIntTipoBase(tintNode2);
        }
	nodeList.add(ptipobaseNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new23() /* reduce ABoolTipoBase */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTipoBase ptipobaseNode1;
        {
            // Block
        TBool tboolNode2;
        tboolNode2 = (TBool)nodeArrayList1.get(0);

        ptipobaseNode1 = new ABoolTipoBase(tboolNode2);
        }
	nodeList.add(ptipobaseNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new24() /* reduce ARealTipoBase */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTipoBase ptipobaseNode1;
        {
            // Block
        TReal trealNode2;
        trealNode2 = (TReal)nodeArrayList1.get(0);

        ptipobaseNode1 = new ARealTipoBase(trealNode2);
        }
	nodeList.add(ptipobaseNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new25() /* reduce ADecProcedimento */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecProcedimento pdecprocedimentoNode1;
        {
            // Block
        TProcedure tprocedureNode2;
        TId tidNode3;
        TParE tpareNode4;
        PParametros pparametrosNode5;
        TParD tpardNode6;
        PComando pcomandoNode7;
        tprocedureNode2 = (TProcedure)nodeArrayList1.get(0);
        tidNode3 = (TId)nodeArrayList2.get(0);
        tpareNode4 = (TParE)nodeArrayList3.get(0);
        pparametrosNode5 = (PParametros)nodeArrayList4.get(0);
        tpardNode6 = (TParD)nodeArrayList5.get(0);
        pcomandoNode7 = (PComando)nodeArrayList6.get(0);

        pdecprocedimentoNode1 = new ADecProcedimento(tprocedureNode2, tidNode3, tpareNode4, pparametrosNode5, tpardNode6, pcomandoNode7);
        }
	nodeList.add(pdecprocedimentoNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new26() /* reduce ADecFuncao */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList7 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList6 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList5 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList4 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PDecFuncao pdecfuncaoNode1;
        {
            // Block
        TFunction tfunctionNode2;
        PTipo ptipoNode3;
        TId tidNode4;
        TParE tpareNode5;
        PParametros pparametrosNode6;
        TParD tpardNode7;
        PExp pexpNode8;
        tfunctionNode2 = (TFunction)nodeArrayList1.get(0);
        ptipoNode3 = (PTipo)nodeArrayList2.get(0);
        tidNode4 = (TId)nodeArrayList3.get(0);
        tpareNode5 = (TParE)nodeArrayList4.get(0);
        pparametrosNode6 = (PParametros)nodeArrayList5.get(0);
        tpardNode7 = (TParD)nodeArrayList6.get(0);
        pexpNode8 = (PExp)nodeArrayList7.get(0);

        pdecfuncaoNode1 = new ADecFuncao(tfunctionNode2, ptipoNode3, tidNode4, tpareNode5, pparametrosNode6, tpardNode7, pexpNode8);
        }
	nodeList.add(pdecfuncaoNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new27() /* reduce AVazioParametros */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        PParametros pparametrosNode1;
        {
            // Block

        pparametrosNode1 = new AVazioParametros();
        }
	nodeList.add(pparametrosNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new28() /* reduce AAparametros1Parametros */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PParametros pparametrosNode1;
        {
            // Block
        PParametro pparametroNode2;
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        pparametroNode2 = (PParametro)nodeArrayList1.get(0);
        {
            // Block
        }

        pparametrosNode1 = new AParametros(pparametroNode2, listNode3);
        }
	nodeList.add(pparametrosNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new29() /* reduce AAparametros2Parametros */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PParametros pparametrosNode1;
        {
            // Block
        PParametro pparametroNode2;
        LinkedList<Object> listNode4 = new LinkedList<Object>();
        pparametroNode2 = (PParametro)nodeArrayList1.get(0);
        {
            // Block
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        listNode3 = (LinkedList)nodeArrayList2.get(0);
	if(listNode3 != null)
	{
	  listNode4.addAll(listNode3);
	}
        }

        pparametrosNode1 = new AParametros(pparametroNode2, listNode4);
        }
	nodeList.add(pparametrosNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new30() /* reduce AAparametro1Parametro */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PParametro pparametroNode1;
        {
            // Block
        @SuppressWarnings("unused") Object nullNode2 = null;
        PTipoParametro ptipoparametroNode3;
        TId tidNode4;
        ptipoparametroNode3 = (PTipoParametro)nodeArrayList1.get(0);
        tidNode4 = (TId)nodeArrayList2.get(0);

        pparametroNode1 = new AParametro(null, ptipoparametroNode3, tidNode4);
        }
	nodeList.add(pparametroNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new31() /* reduce AAparametro2Parametro */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PParametro pparametroNode1;
        {
            // Block
        TVar tvarNode2;
        PTipoParametro ptipoparametroNode3;
        TId tidNode4;
        tvarNode2 = (TVar)nodeArrayList1.get(0);
        ptipoparametroNode3 = (PTipoParametro)nodeArrayList2.get(0);
        tidNode4 = (TId)nodeArrayList3.get(0);

        pparametroNode1 = new AParametro(tvarNode2, ptipoparametroNode3, tidNode4);
        }
	nodeList.add(pparametroNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new32() /* reduce ATipoBaseParamTipoParametro */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTipoParametro ptipoparametroNode1;
        {
            // Block
        PTipoBase ptipobaseNode2;
        ptipobaseNode2 = (PTipoBase)nodeArrayList1.get(0);

        ptipoparametroNode1 = new ATipoBaseParamTipoParametro(ptipobaseNode2);
        }
	nodeList.add(ptipoparametroNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new33() /* reduce ATipoParamContTipoParametro */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PTipoParametro ptipoparametroNode1;
        {
            // Block
        PTipoParametro ptipoparametroNode2;
        TColcheteE tcolcheteeNode3;
        TColcheteD tcolchetedNode4;
        ptipoparametroNode2 = (PTipoParametro)nodeArrayList1.get(0);
        tcolcheteeNode3 = (TColcheteE)nodeArrayList2.get(0);
        tcolchetedNode4 = (TColcheteD)nodeArrayList3.get(0);

        ptipoparametroNode1 = new ATipoParamContTipoParametro(ptipoparametroNode2, tcolcheteeNode3, tcolchetedNode4);
        }
	nodeList.add(ptipoparametroNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new34() /* reduce AParametroCont */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PParametroCont pparametrocontNode1;
        {
            // Block
        TPontoVirgula tpontovirgulaNode2;
        PParametro pparametroNode3;
        tpontovirgulaNode2 = (TPontoVirgula)nodeArrayList1.get(0);
        pparametroNode3 = (PParametro)nodeArrayList2.get(0);

        pparametrocontNode1 = new AParametroCont(tpontovirgulaNode2, pparametroNode3);
        }
	nodeList.add(pparametrocontNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new35() /* reduce APorEnquantoVazioComando */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        PComando pcomandoNode1;
        {
            // Block

        pcomandoNode1 = new APorEnquantoVazioComando();
        }
	nodeList.add(pcomandoNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new36() /* reduce AIdOpcaoVar */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        POpcaoVar popcaovarNode1;
        {
            // Block
        TId tidNode2;
        tidNode2 = (TId)nodeArrayList1.get(0);

        popcaovarNode1 = new AIdOpcaoVar(tidNode2);
        }
	nodeList.add(popcaovarNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new37() /* reduce AInicializacaoOpcaoVar */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        POpcaoVar popcaovarNode1;
        {
            // Block
        PInicializacao pinicializacaoNode2;
        pinicializacaoNode2 = (PInicializacao)nodeArrayList1.get(0);

        popcaovarNode1 = new AInicializacaoOpcaoVar(pinicializacaoNode2);
        }
	nodeList.add(popcaovarNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new38() /* reduce AContOpcaoVar */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PContOpcaoVar pcontopcaovarNode1;
        {
            // Block
        TVirgula tvirgulaNode2;
        POpcaoVar popcaovarNode3;
        tvirgulaNode2 = (TVirgula)nodeArrayList1.get(0);
        popcaovarNode3 = (POpcaoVar)nodeArrayList2.get(0);

        pcontopcaovarNode1 = new AContOpcaoVar(tvirgulaNode2, popcaovarNode3);
        }
	nodeList.add(pcontopcaovarNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new39() /* reduce AVazioExp */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        PExp pexpNode1;
        {
            // Block

        pexpNode1 = new AVazioExp();
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new40() /* reduce AContExp */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        PContExp pcontexpNode1;
        {
            // Block
        TPontoVirgula tpontovirgulaNode2;
        PExp pexpNode3;
        tpontovirgulaNode2 = (TPontoVirgula)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList2.get(0);

        pcontexpNode1 = new AContExp(tpontovirgulaNode2, pexpNode3);
        }
	nodeList.add(pcontexpNode1);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new41() /* reduce ATerminal$ContOpcaoVar */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        {
            // Block
        PContOpcaoVar pcontopcaovarNode1;
        pcontopcaovarNode1 = (PContOpcaoVar)nodeArrayList1.get(0);
	if(pcontopcaovarNode1 != null)
	{
	  listNode2.add(pcontopcaovarNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new42() /* reduce ANonTerminal$ContOpcaoVar */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode1 = new LinkedList<Object>();
        PContOpcaoVar pcontopcaovarNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pcontopcaovarNode2 = (PContOpcaoVar)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pcontopcaovarNode2 != null)
	{
	  listNode3.add(pcontopcaovarNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new43() /* reduce ATerminal$ContInicializacao */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        {
            // Block
        PContInicializacao pcontinicializacaoNode1;
        pcontinicializacaoNode1 = (PContInicializacao)nodeArrayList1.get(0);
	if(pcontinicializacaoNode1 != null)
	{
	  listNode2.add(pcontinicializacaoNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new44() /* reduce ANonTerminal$ContInicializacao */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode1 = new LinkedList<Object>();
        PContInicializacao pcontinicializacaoNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pcontinicializacaoNode2 = (PContInicializacao)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pcontinicializacaoNode2 != null)
	{
	  listNode3.add(pcontinicializacaoNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new45() /* reduce ATerminal$ContExp */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        {
            // Block
        PContExp pcontexpNode1;
        pcontexpNode1 = (PContExp)nodeArrayList1.get(0);
	if(pcontexpNode1 != null)
	{
	  listNode2.add(pcontexpNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new46() /* reduce ANonTerminal$ContExp */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode1 = new LinkedList<Object>();
        PContExp pcontexpNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pcontexpNode2 = (PContExp)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pcontexpNode2 != null)
	{
	  listNode3.add(pcontexpNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new47() /* reduce ATerminal$ParametroCont */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode2 = new LinkedList<Object>();
        {
            // Block
        PParametroCont pparametrocontNode1;
        pparametrocontNode1 = (PParametroCont)nodeArrayList1.get(0);
	if(pparametrocontNode1 != null)
	{
	  listNode2.add(pparametrocontNode1);
	}
        }
	nodeList.add(listNode2);
        return nodeList;
    }



    @SuppressWarnings({ "unchecked", "rawtypes" })
    ArrayList<Object> new48() /* reduce ANonTerminal$ParametroCont */
    {
        @SuppressWarnings("hiding") ArrayList<Object> nodeList = new ArrayList<Object>();

        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList<Object> nodeArrayList1 = pop();
        LinkedList<Object> listNode3 = new LinkedList<Object>();
        {
            // Block
        LinkedList<Object> listNode1 = new LinkedList<Object>();
        PParametroCont pparametrocontNode2;
        listNode1 = (LinkedList)nodeArrayList1.get(0);
        pparametrocontNode2 = (PParametroCont)nodeArrayList2.get(0);
	if(listNode1 != null)
	{
	  listNode3.addAll(listNode1);
	}
	if(pparametrocontNode2 != null)
	{
	  listNode3.add(pparametrocontNode2);
	}
        }
	nodeList.add(listNode3);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, ERROR, 0}, {9, SHIFT, 1}, {10, SHIFT, 2}, {11, SHIFT, 3}, {12, SHIFT, 4}, },
			{{-1, ERROR, 1}, {33, SHIFT, 11}, },
			{{-1, ERROR, 2}, {0, SHIFT, 12}, {1, SHIFT, 13}, {2, SHIFT, 14}, },
			{{-1, ERROR, 3}, {0, SHIFT, 12}, {1, SHIFT, 13}, {2, SHIFT, 14}, },
			{{-1, ERROR, 4}, {0, SHIFT, 12}, {1, SHIFT, 13}, {2, SHIFT, 14}, },
			{{-1, ERROR, 5}, {36, ACCEPT, -1}, },
			{{-1, REDUCE, 0}, {9, SHIFT, 1}, {10, SHIFT, 2}, {11, SHIFT, 3}, {12, SHIFT, 4}, },
			{{-1, REDUCE, 2}, },
			{{-1, REDUCE, 4}, },
			{{-1, REDUCE, 6}, },
			{{-1, REDUCE, 8}, },
			{{-1, ERROR, 11}, {29, SHIFT, 23}, },
			{{-1, REDUCE, 24}, },
			{{-1, REDUCE, 22}, },
			{{-1, REDUCE, 23}, },
			{{-1, ERROR, 15}, {25, SHIFT, 24}, {33, SHIFT, 25}, },
			{{-1, REDUCE, 20}, },
			{{-1, ERROR, 17}, {25, SHIFT, 24}, {33, SHIFT, 26}, },
			{{-1, ERROR, 18}, {25, SHIFT, 24}, {33, SHIFT, 28}, },
			{{-1, REDUCE, 1}, },
			{{-1, REDUCE, 3}, },
			{{-1, REDUCE, 5}, },
			{{-1, REDUCE, 7}, },
			{{-1, REDUCE, 27}, {0, SHIFT, 12}, {1, SHIFT, 13}, {2, SHIFT, 14}, {12, SHIFT, 31}, },
			{{-1, REDUCE, 39}, },
			{{-1, ERROR, 25}, {29, SHIFT, 37}, },
			{{-1, ERROR, 26}, {13, SHIFT, 38}, },
			{{-1, ERROR, 27}, {31, SHIFT, 39}, {32, SHIFT, 40}, },
			{{-1, REDUCE, 36}, {13, SHIFT, 38}, },
			{{-1, REDUCE, 37}, },
			{{-1, ERROR, 30}, {31, SHIFT, 43}, {32, SHIFT, 44}, },
			{{-1, ERROR, 31}, {0, SHIFT, 12}, {1, SHIFT, 13}, {2, SHIFT, 14}, },
			{{-1, REDUCE, 32}, },
			{{-1, ERROR, 33}, {30, SHIFT, 48}, },
			{{-1, REDUCE, 28}, {31, SHIFT, 49}, },
			{{-1, ERROR, 35}, {25, SHIFT, 52}, {33, SHIFT, 53}, },
			{{-1, ERROR, 36}, {26, SHIFT, 54}, },
			{{-1, REDUCE, 27}, {0, SHIFT, 12}, {1, SHIFT, 13}, {2, SHIFT, 14}, {12, SHIFT, 31}, },
			{{-1, REDUCE, 39}, },
			{{-1, REDUCE, 11}, },
			{{-1, ERROR, 40}, {33, SHIFT, 26}, },
			{{-1, REDUCE, 43}, },
			{{-1, ERROR, 42}, {31, SHIFT, 58}, {32, SHIFT, 40}, },
			{{-1, REDUCE, 9}, },
			{{-1, ERROR, 44}, {33, SHIFT, 28}, },
			{{-1, REDUCE, 41}, },
			{{-1, ERROR, 46}, {31, SHIFT, 61}, {32, SHIFT, 44}, },
			{{-1, ERROR, 47}, {25, SHIFT, 52}, {33, SHIFT, 63}, },
			{{-1, REDUCE, 35}, },
			{{-1, ERROR, 49}, {0, SHIFT, 12}, {1, SHIFT, 13}, {2, SHIFT, 14}, {12, SHIFT, 31}, },
			{{-1, REDUCE, 47}, },
			{{-1, REDUCE, 29}, {31, SHIFT, 49}, },
			{{-1, ERROR, 52}, {26, SHIFT, 67}, },
			{{-1, REDUCE, 30}, },
			{{-1, REDUCE, 21}, },
			{{-1, ERROR, 55}, {30, SHIFT, 68}, },
			{{-1, REDUCE, 13}, },
			{{-1, REDUCE, 14}, },
			{{-1, REDUCE, 12}, },
			{{-1, REDUCE, 44}, },
			{{-1, REDUCE, 38}, },
			{{-1, REDUCE, 10}, },
			{{-1, REDUCE, 42}, },
			{{-1, REDUCE, 31}, },
			{{-1, REDUCE, 25}, },
			{{-1, REDUCE, 34}, },
			{{-1, REDUCE, 48}, },
			{{-1, REDUCE, 33}, },
			{{-1, REDUCE, 39}, },
			{{-1, REDUCE, 26}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 5}, },
			{{-1, 6}, },
			{{-1, 7}, {6, 19}, },
			{{-1, 8}, {6, 20}, },
			{{-1, 29}, {17, 27}, {40, 57}, },
			{{-1, 41}, {42, 59}, },
			{{-1, -1}, },
			{{-1, -1}, },
			{{-1, -1}, },
			{{-1, 15}, {3, 17}, {4, 18}, },
			{{-1, 32}, {2, 16}, {3, 16}, {4, 16}, },
			{{-1, 9}, {6, 21}, },
			{{-1, 10}, {6, 22}, },
			{{-1, 33}, {37, 55}, },
			{{-1, 34}, {49, 65}, },
			{{-1, 35}, {31, 47}, },
			{{-1, 50}, {51, 66}, },
			{{-1, 64}, },
			{{-1, 30}, {44, 60}, },
			{{-1, 45}, {46, 62}, },
			{{-1, 36}, {38, 56}, {68, 69}, },
			{{-1, -1}, },
			{{-1, 46}, },
			{{-1, 42}, },
			{{-1, -1}, },
			{{-1, 51}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: 'procedure', 'function', 'cons', 'var'",
			"expecting: id",
			"expecting: 'real', 'int', 'bool'",
			"expecting: EOF",
			"expecting: 'procedure', 'function', 'cons', 'var', EOF",
			"expecting: '('",
			"expecting: '[', id",
			"expecting: 'real', 'int', 'bool', 'var', ')'",
			"expecting: ']'",
			"expecting: ':='",
			"expecting: ';', ','",
			"expecting: ':=', ';', ','",
			"expecting: ')'",
			"expecting: ')', ';'",
			"expecting: 'real', 'int', 'bool', 'var'",
        };*/
    private static int[] errors;
/*      {
			0, 1, 2, 2, 2, 3, 4, 4, 4, 4, 4, 5, 6, 6, 6, 6, 6, 6, 6, 4, 4, 4, 4, 7, 8, 5, 9, 10, 11, 10, 10, 2, 6, 12, 13, 6, 8, 7, 10, 4, 1, 10, 10, 4, 1, 10, 10, 6, 4, 14, 13, 13, 8, 13, 6, 12, 10, 10, 4, 10, 10, 4, 10, 13, 4, 13, 13, 6, 4, 4, 
        };*/

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Parser.class.getResourceAsStream("parser.dat")));

            // read actionTable
            int length = s.readInt();
            Parser.actionTable = new int[length][][];
            for(int i = 0; i < Parser.actionTable.length; i++)
            {
                length = s.readInt();
                Parser.actionTable[i] = new int[length][3];
                for(int j = 0; j < Parser.actionTable[i].length; j++)
                {
                for(int k = 0; k < 3; k++)
                {
                    Parser.actionTable[i][j][k] = s.readInt();
                }
                }
            }

            // read gotoTable
            length = s.readInt();
            gotoTable = new int[length][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][2];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                for(int k = 0; k < 2; k++)
                {
                    gotoTable[i][j][k] = s.readInt();
                }
                }
            }

            // read errorMessages
            length = s.readInt();
            errorMessages = new String[length];
            for(int i = 0; i < errorMessages.length; i++)
            {
                length = s.readInt();
                StringBuffer buffer = new StringBuffer();

                for(int j = 0; j < length; j++)
                {
                buffer.append(s.readChar());
                }
                errorMessages[i] = buffer.toString();
            }

            // read errors
            length = s.readInt();
            errors = new int[length];
            for(int i = 0; i < errors.length; i++)
            {
                errors[i] = s.readInt();
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
        }
    }
}
